/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as DashboardRenstraRouteRouteImport } from './routes/_dashboard/renstra/route'
import { Route as DashboardMasterRouteRouteImport } from './routes/_dashboard/master/route'
import { Route as DashboardKonfigurasiRouteRouteImport } from './routes/_dashboard/konfigurasi/route'
import { Route as DashboardIkuRouteRouteImport } from './routes/_dashboard/iku/route'
import { Route as DashboardRenstraIndexRouteImport } from './routes/_dashboard/renstra/index'
import { Route as DashboardRenjaIndexRouteImport } from './routes/_dashboard/renja/index'
import { Route as DashboardRealisasiIndexRouteImport } from './routes/_dashboard/realisasi/index'
import { Route as DashboardMasterIndexRouteImport } from './routes/_dashboard/master/index'
import { Route as DashboardKonfigurasiIndexRouteImport } from './routes/_dashboard/konfigurasi/index'
import { Route as DashboardIkuIndexRouteImport } from './routes/_dashboard/iku/index'
import { Route as DashboardRenstraIoskRouteImport } from './routes/_dashboard/renstra/iosk'
import { Route as DashboardRenstraIopRouteImport } from './routes/_dashboard/renstra/iop'
import { Route as DashboardRenstraIokRouteImport } from './routes/_dashboard/renstra/iok'
import { Route as DashboardMasterRekeningRouteImport } from './routes/_dashboard/master/rekening'
import { Route as DashboardMasterPejabatRouteImport } from './routes/_dashboard/master/pejabat'
import { Route as DashboardMasterPegawaiRouteImport } from './routes/_dashboard/master/pegawai'
import { Route as DashboardMasterOrganisasiRouteImport } from './routes/_dashboard/master/organisasi'
import { Route as DashboardMasterJadwalRouteImport } from './routes/_dashboard/master/jadwal'
import { Route as DashboardKonfigurasiUserRouteImport } from './routes/_dashboard/konfigurasi/user'
import { Route as DashboardKonfigurasiTransferdataRouteImport } from './routes/_dashboard/konfigurasi/transferdata'
import { Route as DashboardIkuIku_taggingRouteImport } from './routes/_dashboard/iku/iku_tagging'
import { Route as DashboardIkuIku_listRouteImport } from './routes/_dashboard/iku/iku_list'
import { Route as DashboardIkuIku_capaianRouteImport } from './routes/_dashboard/iku/iku_capaian'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardRenstraRouteRoute = DashboardRenstraRouteRouteImport.update({
  id: '/renstra',
  path: '/renstra',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMasterRouteRoute = DashboardMasterRouteRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardKonfigurasiRouteRoute =
  DashboardKonfigurasiRouteRouteImport.update({
    id: '/konfigurasi',
    path: '/konfigurasi',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardIkuRouteRoute = DashboardIkuRouteRouteImport.update({
  id: '/iku',
  path: '/iku',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRenstraIndexRoute = DashboardRenstraIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRenstraRouteRoute,
} as any)
const DashboardRenjaIndexRoute = DashboardRenjaIndexRouteImport.update({
  id: '/renja/',
  path: '/renja/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRealisasiIndexRoute = DashboardRealisasiIndexRouteImport.update({
  id: '/realisasi/',
  path: '/realisasi/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMasterIndexRoute = DashboardMasterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardMasterRouteRoute,
} as any)
const DashboardKonfigurasiIndexRoute =
  DashboardKonfigurasiIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardKonfigurasiRouteRoute,
  } as any)
const DashboardIkuIndexRoute = DashboardIkuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardIkuRouteRoute,
} as any)
const DashboardRenstraIoskRoute = DashboardRenstraIoskRouteImport.update({
  id: '/iosk',
  path: '/iosk',
  getParentRoute: () => DashboardRenstraRouteRoute,
} as any)
const DashboardRenstraIopRoute = DashboardRenstraIopRouteImport.update({
  id: '/iop',
  path: '/iop',
  getParentRoute: () => DashboardRenstraRouteRoute,
} as any)
const DashboardRenstraIokRoute = DashboardRenstraIokRouteImport.update({
  id: '/iok',
  path: '/iok',
  getParentRoute: () => DashboardRenstraRouteRoute,
} as any)
const DashboardMasterRekeningRoute = DashboardMasterRekeningRouteImport.update({
  id: '/rekening',
  path: '/rekening',
  getParentRoute: () => DashboardMasterRouteRoute,
} as any)
const DashboardMasterPejabatRoute = DashboardMasterPejabatRouteImport.update({
  id: '/pejabat',
  path: '/pejabat',
  getParentRoute: () => DashboardMasterRouteRoute,
} as any)
const DashboardMasterPegawaiRoute = DashboardMasterPegawaiRouteImport.update({
  id: '/pegawai',
  path: '/pegawai',
  getParentRoute: () => DashboardMasterRouteRoute,
} as any)
const DashboardMasterOrganisasiRoute =
  DashboardMasterOrganisasiRouteImport.update({
    id: '/organisasi',
    path: '/organisasi',
    getParentRoute: () => DashboardMasterRouteRoute,
  } as any)
const DashboardMasterJadwalRoute = DashboardMasterJadwalRouteImport.update({
  id: '/jadwal',
  path: '/jadwal',
  getParentRoute: () => DashboardMasterRouteRoute,
} as any)
const DashboardKonfigurasiUserRoute =
  DashboardKonfigurasiUserRouteImport.update({
    id: '/user',
    path: '/user',
    getParentRoute: () => DashboardKonfigurasiRouteRoute,
  } as any)
const DashboardKonfigurasiTransferdataRoute =
  DashboardKonfigurasiTransferdataRouteImport.update({
    id: '/transferdata',
    path: '/transferdata',
    getParentRoute: () => DashboardKonfigurasiRouteRoute,
  } as any)
const DashboardIkuIku_taggingRoute = DashboardIkuIku_taggingRouteImport.update({
  id: '/iku_tagging',
  path: '/iku_tagging',
  getParentRoute: () => DashboardIkuRouteRoute,
} as any)
const DashboardIkuIku_listRoute = DashboardIkuIku_listRouteImport.update({
  id: '/iku_list',
  path: '/iku_list',
  getParentRoute: () => DashboardIkuRouteRoute,
} as any)
const DashboardIkuIku_capaianRoute = DashboardIkuIku_capaianRouteImport.update({
  id: '/iku_capaian',
  path: '/iku_capaian',
  getParentRoute: () => DashboardIkuRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteRouteWithChildren
  '/iku': typeof DashboardIkuRouteRouteWithChildren
  '/konfigurasi': typeof DashboardKonfigurasiRouteRouteWithChildren
  '/master': typeof DashboardMasterRouteRouteWithChildren
  '/renstra': typeof DashboardRenstraRouteRouteWithChildren
  '/auth/logout': typeof AuthLogoutRoute
  '/': typeof DashboardIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/iku/iku_capaian': typeof DashboardIkuIku_capaianRoute
  '/iku/iku_list': typeof DashboardIkuIku_listRoute
  '/iku/iku_tagging': typeof DashboardIkuIku_taggingRoute
  '/konfigurasi/transferdata': typeof DashboardKonfigurasiTransferdataRoute
  '/konfigurasi/user': typeof DashboardKonfigurasiUserRoute
  '/master/jadwal': typeof DashboardMasterJadwalRoute
  '/master/organisasi': typeof DashboardMasterOrganisasiRoute
  '/master/pegawai': typeof DashboardMasterPegawaiRoute
  '/master/pejabat': typeof DashboardMasterPejabatRoute
  '/master/rekening': typeof DashboardMasterRekeningRoute
  '/renstra/iok': typeof DashboardRenstraIokRoute
  '/renstra/iop': typeof DashboardRenstraIopRoute
  '/renstra/iosk': typeof DashboardRenstraIoskRoute
  '/iku/': typeof DashboardIkuIndexRoute
  '/konfigurasi/': typeof DashboardKonfigurasiIndexRoute
  '/master/': typeof DashboardMasterIndexRoute
  '/realisasi': typeof DashboardRealisasiIndexRoute
  '/renja': typeof DashboardRenjaIndexRoute
  '/renstra/': typeof DashboardRenstraIndexRoute
}
export interface FileRoutesByTo {
  '/auth/logout': typeof AuthLogoutRoute
  '/': typeof DashboardIndexRoute
  '/auth': typeof AuthIndexRoute
  '/iku/iku_capaian': typeof DashboardIkuIku_capaianRoute
  '/iku/iku_list': typeof DashboardIkuIku_listRoute
  '/iku/iku_tagging': typeof DashboardIkuIku_taggingRoute
  '/konfigurasi/transferdata': typeof DashboardKonfigurasiTransferdataRoute
  '/konfigurasi/user': typeof DashboardKonfigurasiUserRoute
  '/master/jadwal': typeof DashboardMasterJadwalRoute
  '/master/organisasi': typeof DashboardMasterOrganisasiRoute
  '/master/pegawai': typeof DashboardMasterPegawaiRoute
  '/master/pejabat': typeof DashboardMasterPejabatRoute
  '/master/rekening': typeof DashboardMasterRekeningRoute
  '/renstra/iok': typeof DashboardRenstraIokRoute
  '/renstra/iop': typeof DashboardRenstraIopRoute
  '/renstra/iosk': typeof DashboardRenstraIoskRoute
  '/iku': typeof DashboardIkuIndexRoute
  '/konfigurasi': typeof DashboardKonfigurasiIndexRoute
  '/master': typeof DashboardMasterIndexRoute
  '/realisasi': typeof DashboardRealisasiIndexRoute
  '/renja': typeof DashboardRenjaIndexRoute
  '/renstra': typeof DashboardRenstraIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/_dashboard/iku': typeof DashboardIkuRouteRouteWithChildren
  '/_dashboard/konfigurasi': typeof DashboardKonfigurasiRouteRouteWithChildren
  '/_dashboard/master': typeof DashboardMasterRouteRouteWithChildren
  '/_dashboard/renstra': typeof DashboardRenstraRouteRouteWithChildren
  '/auth/logout': typeof AuthLogoutRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_dashboard/iku/iku_capaian': typeof DashboardIkuIku_capaianRoute
  '/_dashboard/iku/iku_list': typeof DashboardIkuIku_listRoute
  '/_dashboard/iku/iku_tagging': typeof DashboardIkuIku_taggingRoute
  '/_dashboard/konfigurasi/transferdata': typeof DashboardKonfigurasiTransferdataRoute
  '/_dashboard/konfigurasi/user': typeof DashboardKonfigurasiUserRoute
  '/_dashboard/master/jadwal': typeof DashboardMasterJadwalRoute
  '/_dashboard/master/organisasi': typeof DashboardMasterOrganisasiRoute
  '/_dashboard/master/pegawai': typeof DashboardMasterPegawaiRoute
  '/_dashboard/master/pejabat': typeof DashboardMasterPejabatRoute
  '/_dashboard/master/rekening': typeof DashboardMasterRekeningRoute
  '/_dashboard/renstra/iok': typeof DashboardRenstraIokRoute
  '/_dashboard/renstra/iop': typeof DashboardRenstraIopRoute
  '/_dashboard/renstra/iosk': typeof DashboardRenstraIoskRoute
  '/_dashboard/iku/': typeof DashboardIkuIndexRoute
  '/_dashboard/konfigurasi/': typeof DashboardKonfigurasiIndexRoute
  '/_dashboard/master/': typeof DashboardMasterIndexRoute
  '/_dashboard/realisasi/': typeof DashboardRealisasiIndexRoute
  '/_dashboard/renja/': typeof DashboardRenjaIndexRoute
  '/_dashboard/renstra/': typeof DashboardRenstraIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/iku'
    | '/konfigurasi'
    | '/master'
    | '/renstra'
    | '/auth/logout'
    | '/'
    | '/auth/'
    | '/iku/iku_capaian'
    | '/iku/iku_list'
    | '/iku/iku_tagging'
    | '/konfigurasi/transferdata'
    | '/konfigurasi/user'
    | '/master/jadwal'
    | '/master/organisasi'
    | '/master/pegawai'
    | '/master/pejabat'
    | '/master/rekening'
    | '/renstra/iok'
    | '/renstra/iop'
    | '/renstra/iosk'
    | '/iku/'
    | '/konfigurasi/'
    | '/master/'
    | '/realisasi'
    | '/renja'
    | '/renstra/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/logout'
    | '/'
    | '/auth'
    | '/iku/iku_capaian'
    | '/iku/iku_list'
    | '/iku/iku_tagging'
    | '/konfigurasi/transferdata'
    | '/konfigurasi/user'
    | '/master/jadwal'
    | '/master/organisasi'
    | '/master/pegawai'
    | '/master/pejabat'
    | '/master/rekening'
    | '/renstra/iok'
    | '/renstra/iop'
    | '/renstra/iosk'
    | '/iku'
    | '/konfigurasi'
    | '/master'
    | '/realisasi'
    | '/renja'
    | '/renstra'
  id:
    | '__root__'
    | '/_dashboard'
    | '/auth'
    | '/_dashboard/iku'
    | '/_dashboard/konfigurasi'
    | '/_dashboard/master'
    | '/_dashboard/renstra'
    | '/auth/logout'
    | '/_dashboard/'
    | '/auth/'
    | '/_dashboard/iku/iku_capaian'
    | '/_dashboard/iku/iku_list'
    | '/_dashboard/iku/iku_tagging'
    | '/_dashboard/konfigurasi/transferdata'
    | '/_dashboard/konfigurasi/user'
    | '/_dashboard/master/jadwal'
    | '/_dashboard/master/organisasi'
    | '/_dashboard/master/pegawai'
    | '/_dashboard/master/pejabat'
    | '/_dashboard/master/rekening'
    | '/_dashboard/renstra/iok'
    | '/_dashboard/renstra/iop'
    | '/_dashboard/renstra/iosk'
    | '/_dashboard/iku/'
    | '/_dashboard/konfigurasi/'
    | '/_dashboard/master/'
    | '/_dashboard/realisasi/'
    | '/_dashboard/renja/'
    | '/_dashboard/renstra/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_dashboard/renstra': {
      id: '/_dashboard/renstra'
      path: '/renstra'
      fullPath: '/renstra'
      preLoaderRoute: typeof DashboardRenstraRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/master': {
      id: '/_dashboard/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof DashboardMasterRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/konfigurasi': {
      id: '/_dashboard/konfigurasi'
      path: '/konfigurasi'
      fullPath: '/konfigurasi'
      preLoaderRoute: typeof DashboardKonfigurasiRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/iku': {
      id: '/_dashboard/iku'
      path: '/iku'
      fullPath: '/iku'
      preLoaderRoute: typeof DashboardIkuRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/renstra/': {
      id: '/_dashboard/renstra/'
      path: '/'
      fullPath: '/renstra/'
      preLoaderRoute: typeof DashboardRenstraIndexRouteImport
      parentRoute: typeof DashboardRenstraRouteRoute
    }
    '/_dashboard/renja/': {
      id: '/_dashboard/renja/'
      path: '/renja'
      fullPath: '/renja'
      preLoaderRoute: typeof DashboardRenjaIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/realisasi/': {
      id: '/_dashboard/realisasi/'
      path: '/realisasi'
      fullPath: '/realisasi'
      preLoaderRoute: typeof DashboardRealisasiIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/master/': {
      id: '/_dashboard/master/'
      path: '/'
      fullPath: '/master/'
      preLoaderRoute: typeof DashboardMasterIndexRouteImport
      parentRoute: typeof DashboardMasterRouteRoute
    }
    '/_dashboard/konfigurasi/': {
      id: '/_dashboard/konfigurasi/'
      path: '/'
      fullPath: '/konfigurasi/'
      preLoaderRoute: typeof DashboardKonfigurasiIndexRouteImport
      parentRoute: typeof DashboardKonfigurasiRouteRoute
    }
    '/_dashboard/iku/': {
      id: '/_dashboard/iku/'
      path: '/'
      fullPath: '/iku/'
      preLoaderRoute: typeof DashboardIkuIndexRouteImport
      parentRoute: typeof DashboardIkuRouteRoute
    }
    '/_dashboard/renstra/iosk': {
      id: '/_dashboard/renstra/iosk'
      path: '/iosk'
      fullPath: '/renstra/iosk'
      preLoaderRoute: typeof DashboardRenstraIoskRouteImport
      parentRoute: typeof DashboardRenstraRouteRoute
    }
    '/_dashboard/renstra/iop': {
      id: '/_dashboard/renstra/iop'
      path: '/iop'
      fullPath: '/renstra/iop'
      preLoaderRoute: typeof DashboardRenstraIopRouteImport
      parentRoute: typeof DashboardRenstraRouteRoute
    }
    '/_dashboard/renstra/iok': {
      id: '/_dashboard/renstra/iok'
      path: '/iok'
      fullPath: '/renstra/iok'
      preLoaderRoute: typeof DashboardRenstraIokRouteImport
      parentRoute: typeof DashboardRenstraRouteRoute
    }
    '/_dashboard/master/rekening': {
      id: '/_dashboard/master/rekening'
      path: '/rekening'
      fullPath: '/master/rekening'
      preLoaderRoute: typeof DashboardMasterRekeningRouteImport
      parentRoute: typeof DashboardMasterRouteRoute
    }
    '/_dashboard/master/pejabat': {
      id: '/_dashboard/master/pejabat'
      path: '/pejabat'
      fullPath: '/master/pejabat'
      preLoaderRoute: typeof DashboardMasterPejabatRouteImport
      parentRoute: typeof DashboardMasterRouteRoute
    }
    '/_dashboard/master/pegawai': {
      id: '/_dashboard/master/pegawai'
      path: '/pegawai'
      fullPath: '/master/pegawai'
      preLoaderRoute: typeof DashboardMasterPegawaiRouteImport
      parentRoute: typeof DashboardMasterRouteRoute
    }
    '/_dashboard/master/organisasi': {
      id: '/_dashboard/master/organisasi'
      path: '/organisasi'
      fullPath: '/master/organisasi'
      preLoaderRoute: typeof DashboardMasterOrganisasiRouteImport
      parentRoute: typeof DashboardMasterRouteRoute
    }
    '/_dashboard/master/jadwal': {
      id: '/_dashboard/master/jadwal'
      path: '/jadwal'
      fullPath: '/master/jadwal'
      preLoaderRoute: typeof DashboardMasterJadwalRouteImport
      parentRoute: typeof DashboardMasterRouteRoute
    }
    '/_dashboard/konfigurasi/user': {
      id: '/_dashboard/konfigurasi/user'
      path: '/user'
      fullPath: '/konfigurasi/user'
      preLoaderRoute: typeof DashboardKonfigurasiUserRouteImport
      parentRoute: typeof DashboardKonfigurasiRouteRoute
    }
    '/_dashboard/konfigurasi/transferdata': {
      id: '/_dashboard/konfigurasi/transferdata'
      path: '/transferdata'
      fullPath: '/konfigurasi/transferdata'
      preLoaderRoute: typeof DashboardKonfigurasiTransferdataRouteImport
      parentRoute: typeof DashboardKonfigurasiRouteRoute
    }
    '/_dashboard/iku/iku_tagging': {
      id: '/_dashboard/iku/iku_tagging'
      path: '/iku_tagging'
      fullPath: '/iku/iku_tagging'
      preLoaderRoute: typeof DashboardIkuIku_taggingRouteImport
      parentRoute: typeof DashboardIkuRouteRoute
    }
    '/_dashboard/iku/iku_list': {
      id: '/_dashboard/iku/iku_list'
      path: '/iku_list'
      fullPath: '/iku/iku_list'
      preLoaderRoute: typeof DashboardIkuIku_listRouteImport
      parentRoute: typeof DashboardIkuRouteRoute
    }
    '/_dashboard/iku/iku_capaian': {
      id: '/_dashboard/iku/iku_capaian'
      path: '/iku_capaian'
      fullPath: '/iku/iku_capaian'
      preLoaderRoute: typeof DashboardIkuIku_capaianRouteImport
      parentRoute: typeof DashboardIkuRouteRoute
    }
  }
}

interface DashboardIkuRouteRouteChildren {
  DashboardIkuIku_capaianRoute: typeof DashboardIkuIku_capaianRoute
  DashboardIkuIku_listRoute: typeof DashboardIkuIku_listRoute
  DashboardIkuIku_taggingRoute: typeof DashboardIkuIku_taggingRoute
  DashboardIkuIndexRoute: typeof DashboardIkuIndexRoute
}

const DashboardIkuRouteRouteChildren: DashboardIkuRouteRouteChildren = {
  DashboardIkuIku_capaianRoute: DashboardIkuIku_capaianRoute,
  DashboardIkuIku_listRoute: DashboardIkuIku_listRoute,
  DashboardIkuIku_taggingRoute: DashboardIkuIku_taggingRoute,
  DashboardIkuIndexRoute: DashboardIkuIndexRoute,
}

const DashboardIkuRouteRouteWithChildren =
  DashboardIkuRouteRoute._addFileChildren(DashboardIkuRouteRouteChildren)

interface DashboardKonfigurasiRouteRouteChildren {
  DashboardKonfigurasiTransferdataRoute: typeof DashboardKonfigurasiTransferdataRoute
  DashboardKonfigurasiUserRoute: typeof DashboardKonfigurasiUserRoute
  DashboardKonfigurasiIndexRoute: typeof DashboardKonfigurasiIndexRoute
}

const DashboardKonfigurasiRouteRouteChildren: DashboardKonfigurasiRouteRouteChildren =
  {
    DashboardKonfigurasiTransferdataRoute:
      DashboardKonfigurasiTransferdataRoute,
    DashboardKonfigurasiUserRoute: DashboardKonfigurasiUserRoute,
    DashboardKonfigurasiIndexRoute: DashboardKonfigurasiIndexRoute,
  }

const DashboardKonfigurasiRouteRouteWithChildren =
  DashboardKonfigurasiRouteRoute._addFileChildren(
    DashboardKonfigurasiRouteRouteChildren,
  )

interface DashboardMasterRouteRouteChildren {
  DashboardMasterJadwalRoute: typeof DashboardMasterJadwalRoute
  DashboardMasterOrganisasiRoute: typeof DashboardMasterOrganisasiRoute
  DashboardMasterPegawaiRoute: typeof DashboardMasterPegawaiRoute
  DashboardMasterPejabatRoute: typeof DashboardMasterPejabatRoute
  DashboardMasterRekeningRoute: typeof DashboardMasterRekeningRoute
  DashboardMasterIndexRoute: typeof DashboardMasterIndexRoute
}

const DashboardMasterRouteRouteChildren: DashboardMasterRouteRouteChildren = {
  DashboardMasterJadwalRoute: DashboardMasterJadwalRoute,
  DashboardMasterOrganisasiRoute: DashboardMasterOrganisasiRoute,
  DashboardMasterPegawaiRoute: DashboardMasterPegawaiRoute,
  DashboardMasterPejabatRoute: DashboardMasterPejabatRoute,
  DashboardMasterRekeningRoute: DashboardMasterRekeningRoute,
  DashboardMasterIndexRoute: DashboardMasterIndexRoute,
}

const DashboardMasterRouteRouteWithChildren =
  DashboardMasterRouteRoute._addFileChildren(DashboardMasterRouteRouteChildren)

interface DashboardRenstraRouteRouteChildren {
  DashboardRenstraIokRoute: typeof DashboardRenstraIokRoute
  DashboardRenstraIopRoute: typeof DashboardRenstraIopRoute
  DashboardRenstraIoskRoute: typeof DashboardRenstraIoskRoute
  DashboardRenstraIndexRoute: typeof DashboardRenstraIndexRoute
}

const DashboardRenstraRouteRouteChildren: DashboardRenstraRouteRouteChildren = {
  DashboardRenstraIokRoute: DashboardRenstraIokRoute,
  DashboardRenstraIopRoute: DashboardRenstraIopRoute,
  DashboardRenstraIoskRoute: DashboardRenstraIoskRoute,
  DashboardRenstraIndexRoute: DashboardRenstraIndexRoute,
}

const DashboardRenstraRouteRouteWithChildren =
  DashboardRenstraRouteRoute._addFileChildren(
    DashboardRenstraRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardIkuRouteRoute: typeof DashboardIkuRouteRouteWithChildren
  DashboardKonfigurasiRouteRoute: typeof DashboardKonfigurasiRouteRouteWithChildren
  DashboardMasterRouteRoute: typeof DashboardMasterRouteRouteWithChildren
  DashboardRenstraRouteRoute: typeof DashboardRenstraRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardRealisasiIndexRoute: typeof DashboardRealisasiIndexRoute
  DashboardRenjaIndexRoute: typeof DashboardRenjaIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIkuRouteRoute: DashboardIkuRouteRouteWithChildren,
  DashboardKonfigurasiRouteRoute: DashboardKonfigurasiRouteRouteWithChildren,
  DashboardMasterRouteRoute: DashboardMasterRouteRouteWithChildren,
  DashboardRenstraRouteRoute: DashboardRenstraRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardRealisasiIndexRoute: DashboardRealisasiIndexRoute,
  DashboardRenjaIndexRoute: DashboardRenjaIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLogoutRoute: AuthLogoutRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
