/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as DashboardRkpdRouteRouteImport } from './routes/_dashboard/rkpd/route'
import { Route as DashboardKonfigurasiRouteRouteImport } from './routes/_dashboard/konfigurasi/route'
import { Route as DashboardDakRouteRouteImport } from './routes/_dashboard/dak/route'
import { Route as DashboardRkpdIndexRouteImport } from './routes/_dashboard/rkpd/index'
import { Route as DashboardKonfigurasiIndexRouteImport } from './routes/_dashboard/konfigurasi/index'
import { Route as DashboardDakIndexRouteImport } from './routes/_dashboard/dak/index'
import { Route as DashboardRkpdPagu_indikatifRouteImport } from './routes/_dashboard/rkpd/pagu_indikatif'
import { Route as DashboardRkpdIndikatorRouteImport } from './routes/_dashboard/rkpd/indikator'
import { Route as DashboardRkpdCapaianRouteImport } from './routes/_dashboard/rkpd/capaian'
import { Route as DashboardKonfigurasiUserRouteImport } from './routes/_dashboard/konfigurasi/user'
import { Route as DashboardKonfigurasiSkpdRouteImport } from './routes/_dashboard/konfigurasi/skpd'
import { Route as DashboardKonfigurasiRoleRouteImport } from './routes/_dashboard/konfigurasi/role'
import { Route as DashboardKonfigurasiPeriodeRouteImport } from './routes/_dashboard/konfigurasi/periode'
import { Route as DashboardDakMonitoringRouteImport } from './routes/_dashboard/dak/monitoring'
import { Route as DashboardDakLaporanRouteImport } from './routes/_dashboard/dak/laporan'
import { Route as DashboardDakIdentifikasiRouteImport } from './routes/_dashboard/dak/identifikasi'
import { Route as DashboardDakDaftardakRouteImport } from './routes/_dashboard/dak/daftardak'
import { Route as DashboardRkpdRenstra_rpjmdRouteRouteImport } from './routes/_dashboard/rkpd/renstra_rpjmd/route'
import { Route as DashboardRkpdRenstraRouteRouteImport } from './routes/_dashboard/rkpd/renstra/route'
import { Route as DashboardRkpdRenja_rkpdRouteRouteImport } from './routes/_dashboard/rkpd/renja_rkpd/route'
import { Route as DashboardRkpdIku_ikdRouteRouteImport } from './routes/_dashboard/rkpd/iku_ikd/route'
import { Route as DashboardRkpdIkuRouteRouteImport } from './routes/_dashboard/rkpd/iku/route'
import { Route as DashboardRkpdIkdRouteRouteImport } from './routes/_dashboard/rkpd/ikd/route'
import { Route as DashboardRkpdHasil_evaluasiRouteRouteImport } from './routes/_dashboard/rkpd/hasil_evaluasi/route'
import { Route as DashboardDakMasterRouteRouteImport } from './routes/_dashboard/dak/master/route'
import { Route as DashboardRkpdRenstra_rpjmdIndexRouteImport } from './routes/_dashboard/rkpd/renstra_rpjmd/index'
import { Route as DashboardRkpdRenstraIndexRouteImport } from './routes/_dashboard/rkpd/renstra/index'
import { Route as DashboardRkpdRenja_rkpdIndexRouteImport } from './routes/_dashboard/rkpd/renja_rkpd/index'
import { Route as DashboardRkpdIku_ikdIndexRouteImport } from './routes/_dashboard/rkpd/iku_ikd/index'
import { Route as DashboardRkpdIkuIndexRouteImport } from './routes/_dashboard/rkpd/iku/index'
import { Route as DashboardRkpdIkdIndexRouteImport } from './routes/_dashboard/rkpd/ikd/index'
import { Route as DashboardRkpdHasil_evaluasiIndexRouteImport } from './routes/_dashboard/rkpd/hasil_evaluasi/index'
import { Route as DashboardDakMasterIndexRouteImport } from './routes/_dashboard/dak/master/index'
import { Route as DashboardRkpdRenstra_rpjmdRekeningRouteImport } from './routes/_dashboard/rkpd/renstra_rpjmd/rekening'
import { Route as DashboardRkpdRenstra_rpjmdRealisasiRouteImport } from './routes/_dashboard/rkpd/renstra_rpjmd/realisasi'
import { Route as DashboardRkpdRenstra_rpjmdPagu_indikatorRouteImport } from './routes/_dashboard/rkpd/renstra_rpjmd/pagu_indikator'
import { Route as DashboardRkpdRenstraIoskRouteImport } from './routes/_dashboard/rkpd/renstra/iosk'
import { Route as DashboardRkpdRenstraIopRouteImport } from './routes/_dashboard/rkpd/renstra/iop'
import { Route as DashboardRkpdRenstraIokRouteImport } from './routes/_dashboard/rkpd/renstra/iok'
import { Route as DashboardRkpdRenja_rkpdRenjaRouteImport } from './routes/_dashboard/rkpd/renja_rkpd/renja'
import { Route as DashboardRkpdRenja_rkpdRekeningRouteImport } from './routes/_dashboard/rkpd/renja_rkpd/rekening'
import { Route as DashboardRkpdRenja_rkpdRealisasiRouteImport } from './routes/_dashboard/rkpd/renja_rkpd/realisasi'
import { Route as DashboardRkpdRenja_rkpdPaguRouteImport } from './routes/_dashboard/rkpd/renja_rkpd/pagu'
import { Route as DashboardRkpdRenja_rkpdIndikatorRouteImport } from './routes/_dashboard/rkpd/renja_rkpd/indikator'
import { Route as DashboardRkpdIku_ikdTaggingRouteImport } from './routes/_dashboard/rkpd/iku_ikd/tagging'
import { Route as DashboardRkpdIku_ikdIku_capaianRouteImport } from './routes/_dashboard/rkpd/iku_ikd/iku_capaian'
import { Route as DashboardRkpdIku_ikdIkuRouteImport } from './routes/_dashboard/rkpd/iku_ikd/iku'
import { Route as DashboardRkpdIku_ikdIkd_capaianRouteImport } from './routes/_dashboard/rkpd/iku_ikd/ikd_capaian'
import { Route as DashboardRkpdIku_ikdIkdRouteImport } from './routes/_dashboard/rkpd/iku_ikd/ikd'
import { Route as DashboardRkpdHasil_evaluasiRpjmdRouteImport } from './routes/_dashboard/rkpd/hasil_evaluasi/rpjmd'
import { Route as DashboardRkpdHasil_evaluasiRkpdRouteImport } from './routes/_dashboard/rkpd/hasil_evaluasi/rkpd'
import { Route as DashboardRkpdHasil_evaluasiRenstraRouteImport } from './routes/_dashboard/rkpd/hasil_evaluasi/renstra'
import { Route as DashboardRkpdHasil_evaluasiRenjaRouteImport } from './routes/_dashboard/rkpd/hasil_evaluasi/renja'
import { Route as DashboardDakMasterTahunRouteImport } from './routes/_dashboard/dak/master/tahun'
import { Route as DashboardDakMasterRekeningRouteImport } from './routes/_dashboard/dak/master/rekening'
import { Route as DashboardDakMasterOpdRouteImport } from './routes/_dashboard/dak/master/opd'
import { Route as DashboardDakMasterMasalahRouteImport } from './routes/_dashboard/dak/master/masalah'
import { Route as DashboardDakMasterJenisRouteImport } from './routes/_dashboard/dak/master/jenis'
import { Route as DashboardDakMasterBidangRouteImport } from './routes/_dashboard/dak/master/bidang'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardRkpdRouteRoute = DashboardRkpdRouteRouteImport.update({
  id: '/rkpd',
  path: '/rkpd',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardKonfigurasiRouteRoute =
  DashboardKonfigurasiRouteRouteImport.update({
    id: '/konfigurasi',
    path: '/konfigurasi',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardDakRouteRoute = DashboardDakRouteRouteImport.update({
  id: '/dak',
  path: '/dak',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRkpdIndexRoute = DashboardRkpdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRkpdRouteRoute,
} as any)
const DashboardKonfigurasiIndexRoute =
  DashboardKonfigurasiIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardKonfigurasiRouteRoute,
  } as any)
const DashboardDakIndexRoute = DashboardDakIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardDakRouteRoute,
} as any)
const DashboardRkpdPagu_indikatifRoute =
  DashboardRkpdPagu_indikatifRouteImport.update({
    id: '/pagu_indikatif',
    path: '/pagu_indikatif',
    getParentRoute: () => DashboardRkpdRouteRoute,
  } as any)
const DashboardRkpdIndikatorRoute = DashboardRkpdIndikatorRouteImport.update({
  id: '/indikator',
  path: '/indikator',
  getParentRoute: () => DashboardRkpdRouteRoute,
} as any)
const DashboardRkpdCapaianRoute = DashboardRkpdCapaianRouteImport.update({
  id: '/capaian',
  path: '/capaian',
  getParentRoute: () => DashboardRkpdRouteRoute,
} as any)
const DashboardKonfigurasiUserRoute =
  DashboardKonfigurasiUserRouteImport.update({
    id: '/user',
    path: '/user',
    getParentRoute: () => DashboardKonfigurasiRouteRoute,
  } as any)
const DashboardKonfigurasiSkpdRoute =
  DashboardKonfigurasiSkpdRouteImport.update({
    id: '/skpd',
    path: '/skpd',
    getParentRoute: () => DashboardKonfigurasiRouteRoute,
  } as any)
const DashboardKonfigurasiRoleRoute =
  DashboardKonfigurasiRoleRouteImport.update({
    id: '/role',
    path: '/role',
    getParentRoute: () => DashboardKonfigurasiRouteRoute,
  } as any)
const DashboardKonfigurasiPeriodeRoute =
  DashboardKonfigurasiPeriodeRouteImport.update({
    id: '/periode',
    path: '/periode',
    getParentRoute: () => DashboardKonfigurasiRouteRoute,
  } as any)
const DashboardDakMonitoringRoute = DashboardDakMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => DashboardDakRouteRoute,
} as any)
const DashboardDakLaporanRoute = DashboardDakLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => DashboardDakRouteRoute,
} as any)
const DashboardDakIdentifikasiRoute =
  DashboardDakIdentifikasiRouteImport.update({
    id: '/identifikasi',
    path: '/identifikasi',
    getParentRoute: () => DashboardDakRouteRoute,
  } as any)
const DashboardDakDaftardakRoute = DashboardDakDaftardakRouteImport.update({
  id: '/daftardak',
  path: '/daftardak',
  getParentRoute: () => DashboardDakRouteRoute,
} as any)
const DashboardRkpdRenstra_rpjmdRouteRoute =
  DashboardRkpdRenstra_rpjmdRouteRouteImport.update({
    id: '/renstra_rpjmd',
    path: '/renstra_rpjmd',
    getParentRoute: () => DashboardRkpdRouteRoute,
  } as any)
const DashboardRkpdRenstraRouteRoute =
  DashboardRkpdRenstraRouteRouteImport.update({
    id: '/renstra',
    path: '/renstra',
    getParentRoute: () => DashboardRkpdRouteRoute,
  } as any)
const DashboardRkpdRenja_rkpdRouteRoute =
  DashboardRkpdRenja_rkpdRouteRouteImport.update({
    id: '/renja_rkpd',
    path: '/renja_rkpd',
    getParentRoute: () => DashboardRkpdRouteRoute,
  } as any)
const DashboardRkpdIku_ikdRouteRoute =
  DashboardRkpdIku_ikdRouteRouteImport.update({
    id: '/iku_ikd',
    path: '/iku_ikd',
    getParentRoute: () => DashboardRkpdRouteRoute,
  } as any)
const DashboardRkpdIkuRouteRoute = DashboardRkpdIkuRouteRouteImport.update({
  id: '/iku',
  path: '/iku',
  getParentRoute: () => DashboardRkpdRouteRoute,
} as any)
const DashboardRkpdIkdRouteRoute = DashboardRkpdIkdRouteRouteImport.update({
  id: '/ikd',
  path: '/ikd',
  getParentRoute: () => DashboardRkpdRouteRoute,
} as any)
const DashboardRkpdHasil_evaluasiRouteRoute =
  DashboardRkpdHasil_evaluasiRouteRouteImport.update({
    id: '/hasil_evaluasi',
    path: '/hasil_evaluasi',
    getParentRoute: () => DashboardRkpdRouteRoute,
  } as any)
const DashboardDakMasterRouteRoute = DashboardDakMasterRouteRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => DashboardDakRouteRoute,
} as any)
const DashboardRkpdRenstra_rpjmdIndexRoute =
  DashboardRkpdRenstra_rpjmdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardRkpdRenstra_rpjmdRouteRoute,
  } as any)
const DashboardRkpdRenstraIndexRoute =
  DashboardRkpdRenstraIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardRkpdRenstraRouteRoute,
  } as any)
const DashboardRkpdRenja_rkpdIndexRoute =
  DashboardRkpdRenja_rkpdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardRkpdRenja_rkpdRouteRoute,
  } as any)
const DashboardRkpdIku_ikdIndexRoute =
  DashboardRkpdIku_ikdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardRkpdIku_ikdRouteRoute,
  } as any)
const DashboardRkpdIkuIndexRoute = DashboardRkpdIkuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRkpdIkuRouteRoute,
} as any)
const DashboardRkpdIkdIndexRoute = DashboardRkpdIkdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRkpdIkdRouteRoute,
} as any)
const DashboardRkpdHasil_evaluasiIndexRoute =
  DashboardRkpdHasil_evaluasiIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardRkpdHasil_evaluasiRouteRoute,
  } as any)
const DashboardDakMasterIndexRoute = DashboardDakMasterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardDakMasterRouteRoute,
} as any)
const DashboardRkpdRenstra_rpjmdRekeningRoute =
  DashboardRkpdRenstra_rpjmdRekeningRouteImport.update({
    id: '/rekening',
    path: '/rekening',
    getParentRoute: () => DashboardRkpdRenstra_rpjmdRouteRoute,
  } as any)
const DashboardRkpdRenstra_rpjmdRealisasiRoute =
  DashboardRkpdRenstra_rpjmdRealisasiRouteImport.update({
    id: '/realisasi',
    path: '/realisasi',
    getParentRoute: () => DashboardRkpdRenstra_rpjmdRouteRoute,
  } as any)
const DashboardRkpdRenstra_rpjmdPagu_indikatorRoute =
  DashboardRkpdRenstra_rpjmdPagu_indikatorRouteImport.update({
    id: '/pagu_indikator',
    path: '/pagu_indikator',
    getParentRoute: () => DashboardRkpdRenstra_rpjmdRouteRoute,
  } as any)
const DashboardRkpdRenstraIoskRoute =
  DashboardRkpdRenstraIoskRouteImport.update({
    id: '/iosk',
    path: '/iosk',
    getParentRoute: () => DashboardRkpdRenstraRouteRoute,
  } as any)
const DashboardRkpdRenstraIopRoute = DashboardRkpdRenstraIopRouteImport.update({
  id: '/iop',
  path: '/iop',
  getParentRoute: () => DashboardRkpdRenstraRouteRoute,
} as any)
const DashboardRkpdRenstraIokRoute = DashboardRkpdRenstraIokRouteImport.update({
  id: '/iok',
  path: '/iok',
  getParentRoute: () => DashboardRkpdRenstraRouteRoute,
} as any)
const DashboardRkpdRenja_rkpdRenjaRoute =
  DashboardRkpdRenja_rkpdRenjaRouteImport.update({
    id: '/renja',
    path: '/renja',
    getParentRoute: () => DashboardRkpdRenja_rkpdRouteRoute,
  } as any)
const DashboardRkpdRenja_rkpdRekeningRoute =
  DashboardRkpdRenja_rkpdRekeningRouteImport.update({
    id: '/rekening',
    path: '/rekening',
    getParentRoute: () => DashboardRkpdRenja_rkpdRouteRoute,
  } as any)
const DashboardRkpdRenja_rkpdRealisasiRoute =
  DashboardRkpdRenja_rkpdRealisasiRouteImport.update({
    id: '/realisasi',
    path: '/realisasi',
    getParentRoute: () => DashboardRkpdRenja_rkpdRouteRoute,
  } as any)
const DashboardRkpdRenja_rkpdPaguRoute =
  DashboardRkpdRenja_rkpdPaguRouteImport.update({
    id: '/pagu',
    path: '/pagu',
    getParentRoute: () => DashboardRkpdRenja_rkpdRouteRoute,
  } as any)
const DashboardRkpdRenja_rkpdIndikatorRoute =
  DashboardRkpdRenja_rkpdIndikatorRouteImport.update({
    id: '/indikator',
    path: '/indikator',
    getParentRoute: () => DashboardRkpdRenja_rkpdRouteRoute,
  } as any)
const DashboardRkpdIku_ikdTaggingRoute =
  DashboardRkpdIku_ikdTaggingRouteImport.update({
    id: '/tagging',
    path: '/tagging',
    getParentRoute: () => DashboardRkpdIku_ikdRouteRoute,
  } as any)
const DashboardRkpdIku_ikdIku_capaianRoute =
  DashboardRkpdIku_ikdIku_capaianRouteImport.update({
    id: '/iku_capaian',
    path: '/iku_capaian',
    getParentRoute: () => DashboardRkpdIku_ikdRouteRoute,
  } as any)
const DashboardRkpdIku_ikdIkuRoute = DashboardRkpdIku_ikdIkuRouteImport.update({
  id: '/iku',
  path: '/iku',
  getParentRoute: () => DashboardRkpdIku_ikdRouteRoute,
} as any)
const DashboardRkpdIku_ikdIkd_capaianRoute =
  DashboardRkpdIku_ikdIkd_capaianRouteImport.update({
    id: '/ikd_capaian',
    path: '/ikd_capaian',
    getParentRoute: () => DashboardRkpdIku_ikdRouteRoute,
  } as any)
const DashboardRkpdIku_ikdIkdRoute = DashboardRkpdIku_ikdIkdRouteImport.update({
  id: '/ikd',
  path: '/ikd',
  getParentRoute: () => DashboardRkpdIku_ikdRouteRoute,
} as any)
const DashboardRkpdHasil_evaluasiRpjmdRoute =
  DashboardRkpdHasil_evaluasiRpjmdRouteImport.update({
    id: '/rpjmd',
    path: '/rpjmd',
    getParentRoute: () => DashboardRkpdHasil_evaluasiRouteRoute,
  } as any)
const DashboardRkpdHasil_evaluasiRkpdRoute =
  DashboardRkpdHasil_evaluasiRkpdRouteImport.update({
    id: '/rkpd',
    path: '/rkpd',
    getParentRoute: () => DashboardRkpdHasil_evaluasiRouteRoute,
  } as any)
const DashboardRkpdHasil_evaluasiRenstraRoute =
  DashboardRkpdHasil_evaluasiRenstraRouteImport.update({
    id: '/renstra',
    path: '/renstra',
    getParentRoute: () => DashboardRkpdHasil_evaluasiRouteRoute,
  } as any)
const DashboardRkpdHasil_evaluasiRenjaRoute =
  DashboardRkpdHasil_evaluasiRenjaRouteImport.update({
    id: '/renja',
    path: '/renja',
    getParentRoute: () => DashboardRkpdHasil_evaluasiRouteRoute,
  } as any)
const DashboardDakMasterTahunRoute = DashboardDakMasterTahunRouteImport.update({
  id: '/tahun',
  path: '/tahun',
  getParentRoute: () => DashboardDakMasterRouteRoute,
} as any)
const DashboardDakMasterRekeningRoute =
  DashboardDakMasterRekeningRouteImport.update({
    id: '/rekening',
    path: '/rekening',
    getParentRoute: () => DashboardDakMasterRouteRoute,
  } as any)
const DashboardDakMasterOpdRoute = DashboardDakMasterOpdRouteImport.update({
  id: '/opd',
  path: '/opd',
  getParentRoute: () => DashboardDakMasterRouteRoute,
} as any)
const DashboardDakMasterMasalahRoute =
  DashboardDakMasterMasalahRouteImport.update({
    id: '/masalah',
    path: '/masalah',
    getParentRoute: () => DashboardDakMasterRouteRoute,
  } as any)
const DashboardDakMasterJenisRoute = DashboardDakMasterJenisRouteImport.update({
  id: '/jenis',
  path: '/jenis',
  getParentRoute: () => DashboardDakMasterRouteRoute,
} as any)
const DashboardDakMasterBidangRoute =
  DashboardDakMasterBidangRouteImport.update({
    id: '/bidang',
    path: '/bidang',
    getParentRoute: () => DashboardDakMasterRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteRouteWithChildren
  '/dak': typeof DashboardDakRouteRouteWithChildren
  '/konfigurasi': typeof DashboardKonfigurasiRouteRouteWithChildren
  '/rkpd': typeof DashboardRkpdRouteRouteWithChildren
  '/auth/logout': typeof AuthLogoutRoute
  '/': typeof DashboardIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/dak/master': typeof DashboardDakMasterRouteRouteWithChildren
  '/rkpd/hasil_evaluasi': typeof DashboardRkpdHasil_evaluasiRouteRouteWithChildren
  '/rkpd/ikd': typeof DashboardRkpdIkdRouteRouteWithChildren
  '/rkpd/iku': typeof DashboardRkpdIkuRouteRouteWithChildren
  '/rkpd/iku_ikd': typeof DashboardRkpdIku_ikdRouteRouteWithChildren
  '/rkpd/renja_rkpd': typeof DashboardRkpdRenja_rkpdRouteRouteWithChildren
  '/rkpd/renstra': typeof DashboardRkpdRenstraRouteRouteWithChildren
  '/rkpd/renstra_rpjmd': typeof DashboardRkpdRenstra_rpjmdRouteRouteWithChildren
  '/dak/daftardak': typeof DashboardDakDaftardakRoute
  '/dak/identifikasi': typeof DashboardDakIdentifikasiRoute
  '/dak/laporan': typeof DashboardDakLaporanRoute
  '/dak/monitoring': typeof DashboardDakMonitoringRoute
  '/konfigurasi/periode': typeof DashboardKonfigurasiPeriodeRoute
  '/konfigurasi/role': typeof DashboardKonfigurasiRoleRoute
  '/konfigurasi/skpd': typeof DashboardKonfigurasiSkpdRoute
  '/konfigurasi/user': typeof DashboardKonfigurasiUserRoute
  '/rkpd/capaian': typeof DashboardRkpdCapaianRoute
  '/rkpd/indikator': typeof DashboardRkpdIndikatorRoute
  '/rkpd/pagu_indikatif': typeof DashboardRkpdPagu_indikatifRoute
  '/dak/': typeof DashboardDakIndexRoute
  '/konfigurasi/': typeof DashboardKonfigurasiIndexRoute
  '/rkpd/': typeof DashboardRkpdIndexRoute
  '/dak/master/bidang': typeof DashboardDakMasterBidangRoute
  '/dak/master/jenis': typeof DashboardDakMasterJenisRoute
  '/dak/master/masalah': typeof DashboardDakMasterMasalahRoute
  '/dak/master/opd': typeof DashboardDakMasterOpdRoute
  '/dak/master/rekening': typeof DashboardDakMasterRekeningRoute
  '/dak/master/tahun': typeof DashboardDakMasterTahunRoute
  '/rkpd/hasil_evaluasi/renja': typeof DashboardRkpdHasil_evaluasiRenjaRoute
  '/rkpd/hasil_evaluasi/renstra': typeof DashboardRkpdHasil_evaluasiRenstraRoute
  '/rkpd/hasil_evaluasi/rkpd': typeof DashboardRkpdHasil_evaluasiRkpdRoute
  '/rkpd/hasil_evaluasi/rpjmd': typeof DashboardRkpdHasil_evaluasiRpjmdRoute
  '/rkpd/iku_ikd/ikd': typeof DashboardRkpdIku_ikdIkdRoute
  '/rkpd/iku_ikd/ikd_capaian': typeof DashboardRkpdIku_ikdIkd_capaianRoute
  '/rkpd/iku_ikd/iku': typeof DashboardRkpdIku_ikdIkuRoute
  '/rkpd/iku_ikd/iku_capaian': typeof DashboardRkpdIku_ikdIku_capaianRoute
  '/rkpd/iku_ikd/tagging': typeof DashboardRkpdIku_ikdTaggingRoute
  '/rkpd/renja_rkpd/indikator': typeof DashboardRkpdRenja_rkpdIndikatorRoute
  '/rkpd/renja_rkpd/pagu': typeof DashboardRkpdRenja_rkpdPaguRoute
  '/rkpd/renja_rkpd/realisasi': typeof DashboardRkpdRenja_rkpdRealisasiRoute
  '/rkpd/renja_rkpd/rekening': typeof DashboardRkpdRenja_rkpdRekeningRoute
  '/rkpd/renja_rkpd/renja': typeof DashboardRkpdRenja_rkpdRenjaRoute
  '/rkpd/renstra/iok': typeof DashboardRkpdRenstraIokRoute
  '/rkpd/renstra/iop': typeof DashboardRkpdRenstraIopRoute
  '/rkpd/renstra/iosk': typeof DashboardRkpdRenstraIoskRoute
  '/rkpd/renstra_rpjmd/pagu_indikator': typeof DashboardRkpdRenstra_rpjmdPagu_indikatorRoute
  '/rkpd/renstra_rpjmd/realisasi': typeof DashboardRkpdRenstra_rpjmdRealisasiRoute
  '/rkpd/renstra_rpjmd/rekening': typeof DashboardRkpdRenstra_rpjmdRekeningRoute
  '/dak/master/': typeof DashboardDakMasterIndexRoute
  '/rkpd/hasil_evaluasi/': typeof DashboardRkpdHasil_evaluasiIndexRoute
  '/rkpd/ikd/': typeof DashboardRkpdIkdIndexRoute
  '/rkpd/iku/': typeof DashboardRkpdIkuIndexRoute
  '/rkpd/iku_ikd/': typeof DashboardRkpdIku_ikdIndexRoute
  '/rkpd/renja_rkpd/': typeof DashboardRkpdRenja_rkpdIndexRoute
  '/rkpd/renstra/': typeof DashboardRkpdRenstraIndexRoute
  '/rkpd/renstra_rpjmd/': typeof DashboardRkpdRenstra_rpjmdIndexRoute
}
export interface FileRoutesByTo {
  '/auth/logout': typeof AuthLogoutRoute
  '/': typeof DashboardIndexRoute
  '/auth': typeof AuthIndexRoute
  '/dak/daftardak': typeof DashboardDakDaftardakRoute
  '/dak/identifikasi': typeof DashboardDakIdentifikasiRoute
  '/dak/laporan': typeof DashboardDakLaporanRoute
  '/dak/monitoring': typeof DashboardDakMonitoringRoute
  '/konfigurasi/periode': typeof DashboardKonfigurasiPeriodeRoute
  '/konfigurasi/role': typeof DashboardKonfigurasiRoleRoute
  '/konfigurasi/skpd': typeof DashboardKonfigurasiSkpdRoute
  '/konfigurasi/user': typeof DashboardKonfigurasiUserRoute
  '/rkpd/capaian': typeof DashboardRkpdCapaianRoute
  '/rkpd/indikator': typeof DashboardRkpdIndikatorRoute
  '/rkpd/pagu_indikatif': typeof DashboardRkpdPagu_indikatifRoute
  '/dak': typeof DashboardDakIndexRoute
  '/konfigurasi': typeof DashboardKonfigurasiIndexRoute
  '/rkpd': typeof DashboardRkpdIndexRoute
  '/dak/master/bidang': typeof DashboardDakMasterBidangRoute
  '/dak/master/jenis': typeof DashboardDakMasterJenisRoute
  '/dak/master/masalah': typeof DashboardDakMasterMasalahRoute
  '/dak/master/opd': typeof DashboardDakMasterOpdRoute
  '/dak/master/rekening': typeof DashboardDakMasterRekeningRoute
  '/dak/master/tahun': typeof DashboardDakMasterTahunRoute
  '/rkpd/hasil_evaluasi/renja': typeof DashboardRkpdHasil_evaluasiRenjaRoute
  '/rkpd/hasil_evaluasi/renstra': typeof DashboardRkpdHasil_evaluasiRenstraRoute
  '/rkpd/hasil_evaluasi/rkpd': typeof DashboardRkpdHasil_evaluasiRkpdRoute
  '/rkpd/hasil_evaluasi/rpjmd': typeof DashboardRkpdHasil_evaluasiRpjmdRoute
  '/rkpd/iku_ikd/ikd': typeof DashboardRkpdIku_ikdIkdRoute
  '/rkpd/iku_ikd/ikd_capaian': typeof DashboardRkpdIku_ikdIkd_capaianRoute
  '/rkpd/iku_ikd/iku': typeof DashboardRkpdIku_ikdIkuRoute
  '/rkpd/iku_ikd/iku_capaian': typeof DashboardRkpdIku_ikdIku_capaianRoute
  '/rkpd/iku_ikd/tagging': typeof DashboardRkpdIku_ikdTaggingRoute
  '/rkpd/renja_rkpd/indikator': typeof DashboardRkpdRenja_rkpdIndikatorRoute
  '/rkpd/renja_rkpd/pagu': typeof DashboardRkpdRenja_rkpdPaguRoute
  '/rkpd/renja_rkpd/realisasi': typeof DashboardRkpdRenja_rkpdRealisasiRoute
  '/rkpd/renja_rkpd/rekening': typeof DashboardRkpdRenja_rkpdRekeningRoute
  '/rkpd/renja_rkpd/renja': typeof DashboardRkpdRenja_rkpdRenjaRoute
  '/rkpd/renstra/iok': typeof DashboardRkpdRenstraIokRoute
  '/rkpd/renstra/iop': typeof DashboardRkpdRenstraIopRoute
  '/rkpd/renstra/iosk': typeof DashboardRkpdRenstraIoskRoute
  '/rkpd/renstra_rpjmd/pagu_indikator': typeof DashboardRkpdRenstra_rpjmdPagu_indikatorRoute
  '/rkpd/renstra_rpjmd/realisasi': typeof DashboardRkpdRenstra_rpjmdRealisasiRoute
  '/rkpd/renstra_rpjmd/rekening': typeof DashboardRkpdRenstra_rpjmdRekeningRoute
  '/dak/master': typeof DashboardDakMasterIndexRoute
  '/rkpd/hasil_evaluasi': typeof DashboardRkpdHasil_evaluasiIndexRoute
  '/rkpd/ikd': typeof DashboardRkpdIkdIndexRoute
  '/rkpd/iku': typeof DashboardRkpdIkuIndexRoute
  '/rkpd/iku_ikd': typeof DashboardRkpdIku_ikdIndexRoute
  '/rkpd/renja_rkpd': typeof DashboardRkpdRenja_rkpdIndexRoute
  '/rkpd/renstra': typeof DashboardRkpdRenstraIndexRoute
  '/rkpd/renstra_rpjmd': typeof DashboardRkpdRenstra_rpjmdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/_dashboard/dak': typeof DashboardDakRouteRouteWithChildren
  '/_dashboard/konfigurasi': typeof DashboardKonfigurasiRouteRouteWithChildren
  '/_dashboard/rkpd': typeof DashboardRkpdRouteRouteWithChildren
  '/auth/logout': typeof AuthLogoutRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_dashboard/dak/master': typeof DashboardDakMasterRouteRouteWithChildren
  '/_dashboard/rkpd/hasil_evaluasi': typeof DashboardRkpdHasil_evaluasiRouteRouteWithChildren
  '/_dashboard/rkpd/ikd': typeof DashboardRkpdIkdRouteRouteWithChildren
  '/_dashboard/rkpd/iku': typeof DashboardRkpdIkuRouteRouteWithChildren
  '/_dashboard/rkpd/iku_ikd': typeof DashboardRkpdIku_ikdRouteRouteWithChildren
  '/_dashboard/rkpd/renja_rkpd': typeof DashboardRkpdRenja_rkpdRouteRouteWithChildren
  '/_dashboard/rkpd/renstra': typeof DashboardRkpdRenstraRouteRouteWithChildren
  '/_dashboard/rkpd/renstra_rpjmd': typeof DashboardRkpdRenstra_rpjmdRouteRouteWithChildren
  '/_dashboard/dak/daftardak': typeof DashboardDakDaftardakRoute
  '/_dashboard/dak/identifikasi': typeof DashboardDakIdentifikasiRoute
  '/_dashboard/dak/laporan': typeof DashboardDakLaporanRoute
  '/_dashboard/dak/monitoring': typeof DashboardDakMonitoringRoute
  '/_dashboard/konfigurasi/periode': typeof DashboardKonfigurasiPeriodeRoute
  '/_dashboard/konfigurasi/role': typeof DashboardKonfigurasiRoleRoute
  '/_dashboard/konfigurasi/skpd': typeof DashboardKonfigurasiSkpdRoute
  '/_dashboard/konfigurasi/user': typeof DashboardKonfigurasiUserRoute
  '/_dashboard/rkpd/capaian': typeof DashboardRkpdCapaianRoute
  '/_dashboard/rkpd/indikator': typeof DashboardRkpdIndikatorRoute
  '/_dashboard/rkpd/pagu_indikatif': typeof DashboardRkpdPagu_indikatifRoute
  '/_dashboard/dak/': typeof DashboardDakIndexRoute
  '/_dashboard/konfigurasi/': typeof DashboardKonfigurasiIndexRoute
  '/_dashboard/rkpd/': typeof DashboardRkpdIndexRoute
  '/_dashboard/dak/master/bidang': typeof DashboardDakMasterBidangRoute
  '/_dashboard/dak/master/jenis': typeof DashboardDakMasterJenisRoute
  '/_dashboard/dak/master/masalah': typeof DashboardDakMasterMasalahRoute
  '/_dashboard/dak/master/opd': typeof DashboardDakMasterOpdRoute
  '/_dashboard/dak/master/rekening': typeof DashboardDakMasterRekeningRoute
  '/_dashboard/dak/master/tahun': typeof DashboardDakMasterTahunRoute
  '/_dashboard/rkpd/hasil_evaluasi/renja': typeof DashboardRkpdHasil_evaluasiRenjaRoute
  '/_dashboard/rkpd/hasil_evaluasi/renstra': typeof DashboardRkpdHasil_evaluasiRenstraRoute
  '/_dashboard/rkpd/hasil_evaluasi/rkpd': typeof DashboardRkpdHasil_evaluasiRkpdRoute
  '/_dashboard/rkpd/hasil_evaluasi/rpjmd': typeof DashboardRkpdHasil_evaluasiRpjmdRoute
  '/_dashboard/rkpd/iku_ikd/ikd': typeof DashboardRkpdIku_ikdIkdRoute
  '/_dashboard/rkpd/iku_ikd/ikd_capaian': typeof DashboardRkpdIku_ikdIkd_capaianRoute
  '/_dashboard/rkpd/iku_ikd/iku': typeof DashboardRkpdIku_ikdIkuRoute
  '/_dashboard/rkpd/iku_ikd/iku_capaian': typeof DashboardRkpdIku_ikdIku_capaianRoute
  '/_dashboard/rkpd/iku_ikd/tagging': typeof DashboardRkpdIku_ikdTaggingRoute
  '/_dashboard/rkpd/renja_rkpd/indikator': typeof DashboardRkpdRenja_rkpdIndikatorRoute
  '/_dashboard/rkpd/renja_rkpd/pagu': typeof DashboardRkpdRenja_rkpdPaguRoute
  '/_dashboard/rkpd/renja_rkpd/realisasi': typeof DashboardRkpdRenja_rkpdRealisasiRoute
  '/_dashboard/rkpd/renja_rkpd/rekening': typeof DashboardRkpdRenja_rkpdRekeningRoute
  '/_dashboard/rkpd/renja_rkpd/renja': typeof DashboardRkpdRenja_rkpdRenjaRoute
  '/_dashboard/rkpd/renstra/iok': typeof DashboardRkpdRenstraIokRoute
  '/_dashboard/rkpd/renstra/iop': typeof DashboardRkpdRenstraIopRoute
  '/_dashboard/rkpd/renstra/iosk': typeof DashboardRkpdRenstraIoskRoute
  '/_dashboard/rkpd/renstra_rpjmd/pagu_indikator': typeof DashboardRkpdRenstra_rpjmdPagu_indikatorRoute
  '/_dashboard/rkpd/renstra_rpjmd/realisasi': typeof DashboardRkpdRenstra_rpjmdRealisasiRoute
  '/_dashboard/rkpd/renstra_rpjmd/rekening': typeof DashboardRkpdRenstra_rpjmdRekeningRoute
  '/_dashboard/dak/master/': typeof DashboardDakMasterIndexRoute
  '/_dashboard/rkpd/hasil_evaluasi/': typeof DashboardRkpdHasil_evaluasiIndexRoute
  '/_dashboard/rkpd/ikd/': typeof DashboardRkpdIkdIndexRoute
  '/_dashboard/rkpd/iku/': typeof DashboardRkpdIkuIndexRoute
  '/_dashboard/rkpd/iku_ikd/': typeof DashboardRkpdIku_ikdIndexRoute
  '/_dashboard/rkpd/renja_rkpd/': typeof DashboardRkpdRenja_rkpdIndexRoute
  '/_dashboard/rkpd/renstra/': typeof DashboardRkpdRenstraIndexRoute
  '/_dashboard/rkpd/renstra_rpjmd/': typeof DashboardRkpdRenstra_rpjmdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/dak'
    | '/konfigurasi'
    | '/rkpd'
    | '/auth/logout'
    | '/'
    | '/auth/'
    | '/dak/master'
    | '/rkpd/hasil_evaluasi'
    | '/rkpd/ikd'
    | '/rkpd/iku'
    | '/rkpd/iku_ikd'
    | '/rkpd/renja_rkpd'
    | '/rkpd/renstra'
    | '/rkpd/renstra_rpjmd'
    | '/dak/daftardak'
    | '/dak/identifikasi'
    | '/dak/laporan'
    | '/dak/monitoring'
    | '/konfigurasi/periode'
    | '/konfigurasi/role'
    | '/konfigurasi/skpd'
    | '/konfigurasi/user'
    | '/rkpd/capaian'
    | '/rkpd/indikator'
    | '/rkpd/pagu_indikatif'
    | '/dak/'
    | '/konfigurasi/'
    | '/rkpd/'
    | '/dak/master/bidang'
    | '/dak/master/jenis'
    | '/dak/master/masalah'
    | '/dak/master/opd'
    | '/dak/master/rekening'
    | '/dak/master/tahun'
    | '/rkpd/hasil_evaluasi/renja'
    | '/rkpd/hasil_evaluasi/renstra'
    | '/rkpd/hasil_evaluasi/rkpd'
    | '/rkpd/hasil_evaluasi/rpjmd'
    | '/rkpd/iku_ikd/ikd'
    | '/rkpd/iku_ikd/ikd_capaian'
    | '/rkpd/iku_ikd/iku'
    | '/rkpd/iku_ikd/iku_capaian'
    | '/rkpd/iku_ikd/tagging'
    | '/rkpd/renja_rkpd/indikator'
    | '/rkpd/renja_rkpd/pagu'
    | '/rkpd/renja_rkpd/realisasi'
    | '/rkpd/renja_rkpd/rekening'
    | '/rkpd/renja_rkpd/renja'
    | '/rkpd/renstra/iok'
    | '/rkpd/renstra/iop'
    | '/rkpd/renstra/iosk'
    | '/rkpd/renstra_rpjmd/pagu_indikator'
    | '/rkpd/renstra_rpjmd/realisasi'
    | '/rkpd/renstra_rpjmd/rekening'
    | '/dak/master/'
    | '/rkpd/hasil_evaluasi/'
    | '/rkpd/ikd/'
    | '/rkpd/iku/'
    | '/rkpd/iku_ikd/'
    | '/rkpd/renja_rkpd/'
    | '/rkpd/renstra/'
    | '/rkpd/renstra_rpjmd/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/logout'
    | '/'
    | '/auth'
    | '/dak/daftardak'
    | '/dak/identifikasi'
    | '/dak/laporan'
    | '/dak/monitoring'
    | '/konfigurasi/periode'
    | '/konfigurasi/role'
    | '/konfigurasi/skpd'
    | '/konfigurasi/user'
    | '/rkpd/capaian'
    | '/rkpd/indikator'
    | '/rkpd/pagu_indikatif'
    | '/dak'
    | '/konfigurasi'
    | '/rkpd'
    | '/dak/master/bidang'
    | '/dak/master/jenis'
    | '/dak/master/masalah'
    | '/dak/master/opd'
    | '/dak/master/rekening'
    | '/dak/master/tahun'
    | '/rkpd/hasil_evaluasi/renja'
    | '/rkpd/hasil_evaluasi/renstra'
    | '/rkpd/hasil_evaluasi/rkpd'
    | '/rkpd/hasil_evaluasi/rpjmd'
    | '/rkpd/iku_ikd/ikd'
    | '/rkpd/iku_ikd/ikd_capaian'
    | '/rkpd/iku_ikd/iku'
    | '/rkpd/iku_ikd/iku_capaian'
    | '/rkpd/iku_ikd/tagging'
    | '/rkpd/renja_rkpd/indikator'
    | '/rkpd/renja_rkpd/pagu'
    | '/rkpd/renja_rkpd/realisasi'
    | '/rkpd/renja_rkpd/rekening'
    | '/rkpd/renja_rkpd/renja'
    | '/rkpd/renstra/iok'
    | '/rkpd/renstra/iop'
    | '/rkpd/renstra/iosk'
    | '/rkpd/renstra_rpjmd/pagu_indikator'
    | '/rkpd/renstra_rpjmd/realisasi'
    | '/rkpd/renstra_rpjmd/rekening'
    | '/dak/master'
    | '/rkpd/hasil_evaluasi'
    | '/rkpd/ikd'
    | '/rkpd/iku'
    | '/rkpd/iku_ikd'
    | '/rkpd/renja_rkpd'
    | '/rkpd/renstra'
    | '/rkpd/renstra_rpjmd'
  id:
    | '__root__'
    | '/_dashboard'
    | '/auth'
    | '/_dashboard/dak'
    | '/_dashboard/konfigurasi'
    | '/_dashboard/rkpd'
    | '/auth/logout'
    | '/_dashboard/'
    | '/auth/'
    | '/_dashboard/dak/master'
    | '/_dashboard/rkpd/hasil_evaluasi'
    | '/_dashboard/rkpd/ikd'
    | '/_dashboard/rkpd/iku'
    | '/_dashboard/rkpd/iku_ikd'
    | '/_dashboard/rkpd/renja_rkpd'
    | '/_dashboard/rkpd/renstra'
    | '/_dashboard/rkpd/renstra_rpjmd'
    | '/_dashboard/dak/daftardak'
    | '/_dashboard/dak/identifikasi'
    | '/_dashboard/dak/laporan'
    | '/_dashboard/dak/monitoring'
    | '/_dashboard/konfigurasi/periode'
    | '/_dashboard/konfigurasi/role'
    | '/_dashboard/konfigurasi/skpd'
    | '/_dashboard/konfigurasi/user'
    | '/_dashboard/rkpd/capaian'
    | '/_dashboard/rkpd/indikator'
    | '/_dashboard/rkpd/pagu_indikatif'
    | '/_dashboard/dak/'
    | '/_dashboard/konfigurasi/'
    | '/_dashboard/rkpd/'
    | '/_dashboard/dak/master/bidang'
    | '/_dashboard/dak/master/jenis'
    | '/_dashboard/dak/master/masalah'
    | '/_dashboard/dak/master/opd'
    | '/_dashboard/dak/master/rekening'
    | '/_dashboard/dak/master/tahun'
    | '/_dashboard/rkpd/hasil_evaluasi/renja'
    | '/_dashboard/rkpd/hasil_evaluasi/renstra'
    | '/_dashboard/rkpd/hasil_evaluasi/rkpd'
    | '/_dashboard/rkpd/hasil_evaluasi/rpjmd'
    | '/_dashboard/rkpd/iku_ikd/ikd'
    | '/_dashboard/rkpd/iku_ikd/ikd_capaian'
    | '/_dashboard/rkpd/iku_ikd/iku'
    | '/_dashboard/rkpd/iku_ikd/iku_capaian'
    | '/_dashboard/rkpd/iku_ikd/tagging'
    | '/_dashboard/rkpd/renja_rkpd/indikator'
    | '/_dashboard/rkpd/renja_rkpd/pagu'
    | '/_dashboard/rkpd/renja_rkpd/realisasi'
    | '/_dashboard/rkpd/renja_rkpd/rekening'
    | '/_dashboard/rkpd/renja_rkpd/renja'
    | '/_dashboard/rkpd/renstra/iok'
    | '/_dashboard/rkpd/renstra/iop'
    | '/_dashboard/rkpd/renstra/iosk'
    | '/_dashboard/rkpd/renstra_rpjmd/pagu_indikator'
    | '/_dashboard/rkpd/renstra_rpjmd/realisasi'
    | '/_dashboard/rkpd/renstra_rpjmd/rekening'
    | '/_dashboard/dak/master/'
    | '/_dashboard/rkpd/hasil_evaluasi/'
    | '/_dashboard/rkpd/ikd/'
    | '/_dashboard/rkpd/iku/'
    | '/_dashboard/rkpd/iku_ikd/'
    | '/_dashboard/rkpd/renja_rkpd/'
    | '/_dashboard/rkpd/renstra/'
    | '/_dashboard/rkpd/renstra_rpjmd/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_dashboard/rkpd': {
      id: '/_dashboard/rkpd'
      path: '/rkpd'
      fullPath: '/rkpd'
      preLoaderRoute: typeof DashboardRkpdRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/konfigurasi': {
      id: '/_dashboard/konfigurasi'
      path: '/konfigurasi'
      fullPath: '/konfigurasi'
      preLoaderRoute: typeof DashboardKonfigurasiRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/dak': {
      id: '/_dashboard/dak'
      path: '/dak'
      fullPath: '/dak'
      preLoaderRoute: typeof DashboardDakRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/rkpd/': {
      id: '/_dashboard/rkpd/'
      path: '/'
      fullPath: '/rkpd/'
      preLoaderRoute: typeof DashboardRkpdIndexRouteImport
      parentRoute: typeof DashboardRkpdRouteRoute
    }
    '/_dashboard/konfigurasi/': {
      id: '/_dashboard/konfigurasi/'
      path: '/'
      fullPath: '/konfigurasi/'
      preLoaderRoute: typeof DashboardKonfigurasiIndexRouteImport
      parentRoute: typeof DashboardKonfigurasiRouteRoute
    }
    '/_dashboard/dak/': {
      id: '/_dashboard/dak/'
      path: '/'
      fullPath: '/dak/'
      preLoaderRoute: typeof DashboardDakIndexRouteImport
      parentRoute: typeof DashboardDakRouteRoute
    }
    '/_dashboard/rkpd/pagu_indikatif': {
      id: '/_dashboard/rkpd/pagu_indikatif'
      path: '/pagu_indikatif'
      fullPath: '/rkpd/pagu_indikatif'
      preLoaderRoute: typeof DashboardRkpdPagu_indikatifRouteImport
      parentRoute: typeof DashboardRkpdRouteRoute
    }
    '/_dashboard/rkpd/indikator': {
      id: '/_dashboard/rkpd/indikator'
      path: '/indikator'
      fullPath: '/rkpd/indikator'
      preLoaderRoute: typeof DashboardRkpdIndikatorRouteImport
      parentRoute: typeof DashboardRkpdRouteRoute
    }
    '/_dashboard/rkpd/capaian': {
      id: '/_dashboard/rkpd/capaian'
      path: '/capaian'
      fullPath: '/rkpd/capaian'
      preLoaderRoute: typeof DashboardRkpdCapaianRouteImport
      parentRoute: typeof DashboardRkpdRouteRoute
    }
    '/_dashboard/konfigurasi/user': {
      id: '/_dashboard/konfigurasi/user'
      path: '/user'
      fullPath: '/konfigurasi/user'
      preLoaderRoute: typeof DashboardKonfigurasiUserRouteImport
      parentRoute: typeof DashboardKonfigurasiRouteRoute
    }
    '/_dashboard/konfigurasi/skpd': {
      id: '/_dashboard/konfigurasi/skpd'
      path: '/skpd'
      fullPath: '/konfigurasi/skpd'
      preLoaderRoute: typeof DashboardKonfigurasiSkpdRouteImport
      parentRoute: typeof DashboardKonfigurasiRouteRoute
    }
    '/_dashboard/konfigurasi/role': {
      id: '/_dashboard/konfigurasi/role'
      path: '/role'
      fullPath: '/konfigurasi/role'
      preLoaderRoute: typeof DashboardKonfigurasiRoleRouteImport
      parentRoute: typeof DashboardKonfigurasiRouteRoute
    }
    '/_dashboard/konfigurasi/periode': {
      id: '/_dashboard/konfigurasi/periode'
      path: '/periode'
      fullPath: '/konfigurasi/periode'
      preLoaderRoute: typeof DashboardKonfigurasiPeriodeRouteImport
      parentRoute: typeof DashboardKonfigurasiRouteRoute
    }
    '/_dashboard/dak/monitoring': {
      id: '/_dashboard/dak/monitoring'
      path: '/monitoring'
      fullPath: '/dak/monitoring'
      preLoaderRoute: typeof DashboardDakMonitoringRouteImport
      parentRoute: typeof DashboardDakRouteRoute
    }
    '/_dashboard/dak/laporan': {
      id: '/_dashboard/dak/laporan'
      path: '/laporan'
      fullPath: '/dak/laporan'
      preLoaderRoute: typeof DashboardDakLaporanRouteImport
      parentRoute: typeof DashboardDakRouteRoute
    }
    '/_dashboard/dak/identifikasi': {
      id: '/_dashboard/dak/identifikasi'
      path: '/identifikasi'
      fullPath: '/dak/identifikasi'
      preLoaderRoute: typeof DashboardDakIdentifikasiRouteImport
      parentRoute: typeof DashboardDakRouteRoute
    }
    '/_dashboard/dak/daftardak': {
      id: '/_dashboard/dak/daftardak'
      path: '/daftardak'
      fullPath: '/dak/daftardak'
      preLoaderRoute: typeof DashboardDakDaftardakRouteImport
      parentRoute: typeof DashboardDakRouteRoute
    }
    '/_dashboard/rkpd/renstra_rpjmd': {
      id: '/_dashboard/rkpd/renstra_rpjmd'
      path: '/renstra_rpjmd'
      fullPath: '/rkpd/renstra_rpjmd'
      preLoaderRoute: typeof DashboardRkpdRenstra_rpjmdRouteRouteImport
      parentRoute: typeof DashboardRkpdRouteRoute
    }
    '/_dashboard/rkpd/renstra': {
      id: '/_dashboard/rkpd/renstra'
      path: '/renstra'
      fullPath: '/rkpd/renstra'
      preLoaderRoute: typeof DashboardRkpdRenstraRouteRouteImport
      parentRoute: typeof DashboardRkpdRouteRoute
    }
    '/_dashboard/rkpd/renja_rkpd': {
      id: '/_dashboard/rkpd/renja_rkpd'
      path: '/renja_rkpd'
      fullPath: '/rkpd/renja_rkpd'
      preLoaderRoute: typeof DashboardRkpdRenja_rkpdRouteRouteImport
      parentRoute: typeof DashboardRkpdRouteRoute
    }
    '/_dashboard/rkpd/iku_ikd': {
      id: '/_dashboard/rkpd/iku_ikd'
      path: '/iku_ikd'
      fullPath: '/rkpd/iku_ikd'
      preLoaderRoute: typeof DashboardRkpdIku_ikdRouteRouteImport
      parentRoute: typeof DashboardRkpdRouteRoute
    }
    '/_dashboard/rkpd/iku': {
      id: '/_dashboard/rkpd/iku'
      path: '/iku'
      fullPath: '/rkpd/iku'
      preLoaderRoute: typeof DashboardRkpdIkuRouteRouteImport
      parentRoute: typeof DashboardRkpdRouteRoute
    }
    '/_dashboard/rkpd/ikd': {
      id: '/_dashboard/rkpd/ikd'
      path: '/ikd'
      fullPath: '/rkpd/ikd'
      preLoaderRoute: typeof DashboardRkpdIkdRouteRouteImport
      parentRoute: typeof DashboardRkpdRouteRoute
    }
    '/_dashboard/rkpd/hasil_evaluasi': {
      id: '/_dashboard/rkpd/hasil_evaluasi'
      path: '/hasil_evaluasi'
      fullPath: '/rkpd/hasil_evaluasi'
      preLoaderRoute: typeof DashboardRkpdHasil_evaluasiRouteRouteImport
      parentRoute: typeof DashboardRkpdRouteRoute
    }
    '/_dashboard/dak/master': {
      id: '/_dashboard/dak/master'
      path: '/master'
      fullPath: '/dak/master'
      preLoaderRoute: typeof DashboardDakMasterRouteRouteImport
      parentRoute: typeof DashboardDakRouteRoute
    }
    '/_dashboard/rkpd/renstra_rpjmd/': {
      id: '/_dashboard/rkpd/renstra_rpjmd/'
      path: '/'
      fullPath: '/rkpd/renstra_rpjmd/'
      preLoaderRoute: typeof DashboardRkpdRenstra_rpjmdIndexRouteImport
      parentRoute: typeof DashboardRkpdRenstra_rpjmdRouteRoute
    }
    '/_dashboard/rkpd/renstra/': {
      id: '/_dashboard/rkpd/renstra/'
      path: '/'
      fullPath: '/rkpd/renstra/'
      preLoaderRoute: typeof DashboardRkpdRenstraIndexRouteImport
      parentRoute: typeof DashboardRkpdRenstraRouteRoute
    }
    '/_dashboard/rkpd/renja_rkpd/': {
      id: '/_dashboard/rkpd/renja_rkpd/'
      path: '/'
      fullPath: '/rkpd/renja_rkpd/'
      preLoaderRoute: typeof DashboardRkpdRenja_rkpdIndexRouteImport
      parentRoute: typeof DashboardRkpdRenja_rkpdRouteRoute
    }
    '/_dashboard/rkpd/iku_ikd/': {
      id: '/_dashboard/rkpd/iku_ikd/'
      path: '/'
      fullPath: '/rkpd/iku_ikd/'
      preLoaderRoute: typeof DashboardRkpdIku_ikdIndexRouteImport
      parentRoute: typeof DashboardRkpdIku_ikdRouteRoute
    }
    '/_dashboard/rkpd/iku/': {
      id: '/_dashboard/rkpd/iku/'
      path: '/'
      fullPath: '/rkpd/iku/'
      preLoaderRoute: typeof DashboardRkpdIkuIndexRouteImport
      parentRoute: typeof DashboardRkpdIkuRouteRoute
    }
    '/_dashboard/rkpd/ikd/': {
      id: '/_dashboard/rkpd/ikd/'
      path: '/'
      fullPath: '/rkpd/ikd/'
      preLoaderRoute: typeof DashboardRkpdIkdIndexRouteImport
      parentRoute: typeof DashboardRkpdIkdRouteRoute
    }
    '/_dashboard/rkpd/hasil_evaluasi/': {
      id: '/_dashboard/rkpd/hasil_evaluasi/'
      path: '/'
      fullPath: '/rkpd/hasil_evaluasi/'
      preLoaderRoute: typeof DashboardRkpdHasil_evaluasiIndexRouteImport
      parentRoute: typeof DashboardRkpdHasil_evaluasiRouteRoute
    }
    '/_dashboard/dak/master/': {
      id: '/_dashboard/dak/master/'
      path: '/'
      fullPath: '/dak/master/'
      preLoaderRoute: typeof DashboardDakMasterIndexRouteImport
      parentRoute: typeof DashboardDakMasterRouteRoute
    }
    '/_dashboard/rkpd/renstra_rpjmd/rekening': {
      id: '/_dashboard/rkpd/renstra_rpjmd/rekening'
      path: '/rekening'
      fullPath: '/rkpd/renstra_rpjmd/rekening'
      preLoaderRoute: typeof DashboardRkpdRenstra_rpjmdRekeningRouteImport
      parentRoute: typeof DashboardRkpdRenstra_rpjmdRouteRoute
    }
    '/_dashboard/rkpd/renstra_rpjmd/realisasi': {
      id: '/_dashboard/rkpd/renstra_rpjmd/realisasi'
      path: '/realisasi'
      fullPath: '/rkpd/renstra_rpjmd/realisasi'
      preLoaderRoute: typeof DashboardRkpdRenstra_rpjmdRealisasiRouteImport
      parentRoute: typeof DashboardRkpdRenstra_rpjmdRouteRoute
    }
    '/_dashboard/rkpd/renstra_rpjmd/pagu_indikator': {
      id: '/_dashboard/rkpd/renstra_rpjmd/pagu_indikator'
      path: '/pagu_indikator'
      fullPath: '/rkpd/renstra_rpjmd/pagu_indikator'
      preLoaderRoute: typeof DashboardRkpdRenstra_rpjmdPagu_indikatorRouteImport
      parentRoute: typeof DashboardRkpdRenstra_rpjmdRouteRoute
    }
    '/_dashboard/rkpd/renstra/iosk': {
      id: '/_dashboard/rkpd/renstra/iosk'
      path: '/iosk'
      fullPath: '/rkpd/renstra/iosk'
      preLoaderRoute: typeof DashboardRkpdRenstraIoskRouteImport
      parentRoute: typeof DashboardRkpdRenstraRouteRoute
    }
    '/_dashboard/rkpd/renstra/iop': {
      id: '/_dashboard/rkpd/renstra/iop'
      path: '/iop'
      fullPath: '/rkpd/renstra/iop'
      preLoaderRoute: typeof DashboardRkpdRenstraIopRouteImport
      parentRoute: typeof DashboardRkpdRenstraRouteRoute
    }
    '/_dashboard/rkpd/renstra/iok': {
      id: '/_dashboard/rkpd/renstra/iok'
      path: '/iok'
      fullPath: '/rkpd/renstra/iok'
      preLoaderRoute: typeof DashboardRkpdRenstraIokRouteImport
      parentRoute: typeof DashboardRkpdRenstraRouteRoute
    }
    '/_dashboard/rkpd/renja_rkpd/renja': {
      id: '/_dashboard/rkpd/renja_rkpd/renja'
      path: '/renja'
      fullPath: '/rkpd/renja_rkpd/renja'
      preLoaderRoute: typeof DashboardRkpdRenja_rkpdRenjaRouteImport
      parentRoute: typeof DashboardRkpdRenja_rkpdRouteRoute
    }
    '/_dashboard/rkpd/renja_rkpd/rekening': {
      id: '/_dashboard/rkpd/renja_rkpd/rekening'
      path: '/rekening'
      fullPath: '/rkpd/renja_rkpd/rekening'
      preLoaderRoute: typeof DashboardRkpdRenja_rkpdRekeningRouteImport
      parentRoute: typeof DashboardRkpdRenja_rkpdRouteRoute
    }
    '/_dashboard/rkpd/renja_rkpd/realisasi': {
      id: '/_dashboard/rkpd/renja_rkpd/realisasi'
      path: '/realisasi'
      fullPath: '/rkpd/renja_rkpd/realisasi'
      preLoaderRoute: typeof DashboardRkpdRenja_rkpdRealisasiRouteImport
      parentRoute: typeof DashboardRkpdRenja_rkpdRouteRoute
    }
    '/_dashboard/rkpd/renja_rkpd/pagu': {
      id: '/_dashboard/rkpd/renja_rkpd/pagu'
      path: '/pagu'
      fullPath: '/rkpd/renja_rkpd/pagu'
      preLoaderRoute: typeof DashboardRkpdRenja_rkpdPaguRouteImport
      parentRoute: typeof DashboardRkpdRenja_rkpdRouteRoute
    }
    '/_dashboard/rkpd/renja_rkpd/indikator': {
      id: '/_dashboard/rkpd/renja_rkpd/indikator'
      path: '/indikator'
      fullPath: '/rkpd/renja_rkpd/indikator'
      preLoaderRoute: typeof DashboardRkpdRenja_rkpdIndikatorRouteImport
      parentRoute: typeof DashboardRkpdRenja_rkpdRouteRoute
    }
    '/_dashboard/rkpd/iku_ikd/tagging': {
      id: '/_dashboard/rkpd/iku_ikd/tagging'
      path: '/tagging'
      fullPath: '/rkpd/iku_ikd/tagging'
      preLoaderRoute: typeof DashboardRkpdIku_ikdTaggingRouteImport
      parentRoute: typeof DashboardRkpdIku_ikdRouteRoute
    }
    '/_dashboard/rkpd/iku_ikd/iku_capaian': {
      id: '/_dashboard/rkpd/iku_ikd/iku_capaian'
      path: '/iku_capaian'
      fullPath: '/rkpd/iku_ikd/iku_capaian'
      preLoaderRoute: typeof DashboardRkpdIku_ikdIku_capaianRouteImport
      parentRoute: typeof DashboardRkpdIku_ikdRouteRoute
    }
    '/_dashboard/rkpd/iku_ikd/iku': {
      id: '/_dashboard/rkpd/iku_ikd/iku'
      path: '/iku'
      fullPath: '/rkpd/iku_ikd/iku'
      preLoaderRoute: typeof DashboardRkpdIku_ikdIkuRouteImport
      parentRoute: typeof DashboardRkpdIku_ikdRouteRoute
    }
    '/_dashboard/rkpd/iku_ikd/ikd_capaian': {
      id: '/_dashboard/rkpd/iku_ikd/ikd_capaian'
      path: '/ikd_capaian'
      fullPath: '/rkpd/iku_ikd/ikd_capaian'
      preLoaderRoute: typeof DashboardRkpdIku_ikdIkd_capaianRouteImport
      parentRoute: typeof DashboardRkpdIku_ikdRouteRoute
    }
    '/_dashboard/rkpd/iku_ikd/ikd': {
      id: '/_dashboard/rkpd/iku_ikd/ikd'
      path: '/ikd'
      fullPath: '/rkpd/iku_ikd/ikd'
      preLoaderRoute: typeof DashboardRkpdIku_ikdIkdRouteImport
      parentRoute: typeof DashboardRkpdIku_ikdRouteRoute
    }
    '/_dashboard/rkpd/hasil_evaluasi/rpjmd': {
      id: '/_dashboard/rkpd/hasil_evaluasi/rpjmd'
      path: '/rpjmd'
      fullPath: '/rkpd/hasil_evaluasi/rpjmd'
      preLoaderRoute: typeof DashboardRkpdHasil_evaluasiRpjmdRouteImport
      parentRoute: typeof DashboardRkpdHasil_evaluasiRouteRoute
    }
    '/_dashboard/rkpd/hasil_evaluasi/rkpd': {
      id: '/_dashboard/rkpd/hasil_evaluasi/rkpd'
      path: '/rkpd'
      fullPath: '/rkpd/hasil_evaluasi/rkpd'
      preLoaderRoute: typeof DashboardRkpdHasil_evaluasiRkpdRouteImport
      parentRoute: typeof DashboardRkpdHasil_evaluasiRouteRoute
    }
    '/_dashboard/rkpd/hasil_evaluasi/renstra': {
      id: '/_dashboard/rkpd/hasil_evaluasi/renstra'
      path: '/renstra'
      fullPath: '/rkpd/hasil_evaluasi/renstra'
      preLoaderRoute: typeof DashboardRkpdHasil_evaluasiRenstraRouteImport
      parentRoute: typeof DashboardRkpdHasil_evaluasiRouteRoute
    }
    '/_dashboard/rkpd/hasil_evaluasi/renja': {
      id: '/_dashboard/rkpd/hasil_evaluasi/renja'
      path: '/renja'
      fullPath: '/rkpd/hasil_evaluasi/renja'
      preLoaderRoute: typeof DashboardRkpdHasil_evaluasiRenjaRouteImport
      parentRoute: typeof DashboardRkpdHasil_evaluasiRouteRoute
    }
    '/_dashboard/dak/master/tahun': {
      id: '/_dashboard/dak/master/tahun'
      path: '/tahun'
      fullPath: '/dak/master/tahun'
      preLoaderRoute: typeof DashboardDakMasterTahunRouteImport
      parentRoute: typeof DashboardDakMasterRouteRoute
    }
    '/_dashboard/dak/master/rekening': {
      id: '/_dashboard/dak/master/rekening'
      path: '/rekening'
      fullPath: '/dak/master/rekening'
      preLoaderRoute: typeof DashboardDakMasterRekeningRouteImport
      parentRoute: typeof DashboardDakMasterRouteRoute
    }
    '/_dashboard/dak/master/opd': {
      id: '/_dashboard/dak/master/opd'
      path: '/opd'
      fullPath: '/dak/master/opd'
      preLoaderRoute: typeof DashboardDakMasterOpdRouteImport
      parentRoute: typeof DashboardDakMasterRouteRoute
    }
    '/_dashboard/dak/master/masalah': {
      id: '/_dashboard/dak/master/masalah'
      path: '/masalah'
      fullPath: '/dak/master/masalah'
      preLoaderRoute: typeof DashboardDakMasterMasalahRouteImport
      parentRoute: typeof DashboardDakMasterRouteRoute
    }
    '/_dashboard/dak/master/jenis': {
      id: '/_dashboard/dak/master/jenis'
      path: '/jenis'
      fullPath: '/dak/master/jenis'
      preLoaderRoute: typeof DashboardDakMasterJenisRouteImport
      parentRoute: typeof DashboardDakMasterRouteRoute
    }
    '/_dashboard/dak/master/bidang': {
      id: '/_dashboard/dak/master/bidang'
      path: '/bidang'
      fullPath: '/dak/master/bidang'
      preLoaderRoute: typeof DashboardDakMasterBidangRouteImport
      parentRoute: typeof DashboardDakMasterRouteRoute
    }
  }
}

interface DashboardDakMasterRouteRouteChildren {
  DashboardDakMasterBidangRoute: typeof DashboardDakMasterBidangRoute
  DashboardDakMasterJenisRoute: typeof DashboardDakMasterJenisRoute
  DashboardDakMasterMasalahRoute: typeof DashboardDakMasterMasalahRoute
  DashboardDakMasterOpdRoute: typeof DashboardDakMasterOpdRoute
  DashboardDakMasterRekeningRoute: typeof DashboardDakMasterRekeningRoute
  DashboardDakMasterTahunRoute: typeof DashboardDakMasterTahunRoute
  DashboardDakMasterIndexRoute: typeof DashboardDakMasterIndexRoute
}

const DashboardDakMasterRouteRouteChildren: DashboardDakMasterRouteRouteChildren =
  {
    DashboardDakMasterBidangRoute: DashboardDakMasterBidangRoute,
    DashboardDakMasterJenisRoute: DashboardDakMasterJenisRoute,
    DashboardDakMasterMasalahRoute: DashboardDakMasterMasalahRoute,
    DashboardDakMasterOpdRoute: DashboardDakMasterOpdRoute,
    DashboardDakMasterRekeningRoute: DashboardDakMasterRekeningRoute,
    DashboardDakMasterTahunRoute: DashboardDakMasterTahunRoute,
    DashboardDakMasterIndexRoute: DashboardDakMasterIndexRoute,
  }

const DashboardDakMasterRouteRouteWithChildren =
  DashboardDakMasterRouteRoute._addFileChildren(
    DashboardDakMasterRouteRouteChildren,
  )

interface DashboardDakRouteRouteChildren {
  DashboardDakMasterRouteRoute: typeof DashboardDakMasterRouteRouteWithChildren
  DashboardDakDaftardakRoute: typeof DashboardDakDaftardakRoute
  DashboardDakIdentifikasiRoute: typeof DashboardDakIdentifikasiRoute
  DashboardDakLaporanRoute: typeof DashboardDakLaporanRoute
  DashboardDakMonitoringRoute: typeof DashboardDakMonitoringRoute
  DashboardDakIndexRoute: typeof DashboardDakIndexRoute
}

const DashboardDakRouteRouteChildren: DashboardDakRouteRouteChildren = {
  DashboardDakMasterRouteRoute: DashboardDakMasterRouteRouteWithChildren,
  DashboardDakDaftardakRoute: DashboardDakDaftardakRoute,
  DashboardDakIdentifikasiRoute: DashboardDakIdentifikasiRoute,
  DashboardDakLaporanRoute: DashboardDakLaporanRoute,
  DashboardDakMonitoringRoute: DashboardDakMonitoringRoute,
  DashboardDakIndexRoute: DashboardDakIndexRoute,
}

const DashboardDakRouteRouteWithChildren =
  DashboardDakRouteRoute._addFileChildren(DashboardDakRouteRouteChildren)

interface DashboardKonfigurasiRouteRouteChildren {
  DashboardKonfigurasiPeriodeRoute: typeof DashboardKonfigurasiPeriodeRoute
  DashboardKonfigurasiRoleRoute: typeof DashboardKonfigurasiRoleRoute
  DashboardKonfigurasiSkpdRoute: typeof DashboardKonfigurasiSkpdRoute
  DashboardKonfigurasiUserRoute: typeof DashboardKonfigurasiUserRoute
  DashboardKonfigurasiIndexRoute: typeof DashboardKonfigurasiIndexRoute
}

const DashboardKonfigurasiRouteRouteChildren: DashboardKonfigurasiRouteRouteChildren =
  {
    DashboardKonfigurasiPeriodeRoute: DashboardKonfigurasiPeriodeRoute,
    DashboardKonfigurasiRoleRoute: DashboardKonfigurasiRoleRoute,
    DashboardKonfigurasiSkpdRoute: DashboardKonfigurasiSkpdRoute,
    DashboardKonfigurasiUserRoute: DashboardKonfigurasiUserRoute,
    DashboardKonfigurasiIndexRoute: DashboardKonfigurasiIndexRoute,
  }

const DashboardKonfigurasiRouteRouteWithChildren =
  DashboardKonfigurasiRouteRoute._addFileChildren(
    DashboardKonfigurasiRouteRouteChildren,
  )

interface DashboardRkpdHasil_evaluasiRouteRouteChildren {
  DashboardRkpdHasil_evaluasiRenjaRoute: typeof DashboardRkpdHasil_evaluasiRenjaRoute
  DashboardRkpdHasil_evaluasiRenstraRoute: typeof DashboardRkpdHasil_evaluasiRenstraRoute
  DashboardRkpdHasil_evaluasiRkpdRoute: typeof DashboardRkpdHasil_evaluasiRkpdRoute
  DashboardRkpdHasil_evaluasiRpjmdRoute: typeof DashboardRkpdHasil_evaluasiRpjmdRoute
  DashboardRkpdHasil_evaluasiIndexRoute: typeof DashboardRkpdHasil_evaluasiIndexRoute
}

const DashboardRkpdHasil_evaluasiRouteRouteChildren: DashboardRkpdHasil_evaluasiRouteRouteChildren =
  {
    DashboardRkpdHasil_evaluasiRenjaRoute:
      DashboardRkpdHasil_evaluasiRenjaRoute,
    DashboardRkpdHasil_evaluasiRenstraRoute:
      DashboardRkpdHasil_evaluasiRenstraRoute,
    DashboardRkpdHasil_evaluasiRkpdRoute: DashboardRkpdHasil_evaluasiRkpdRoute,
    DashboardRkpdHasil_evaluasiRpjmdRoute:
      DashboardRkpdHasil_evaluasiRpjmdRoute,
    DashboardRkpdHasil_evaluasiIndexRoute:
      DashboardRkpdHasil_evaluasiIndexRoute,
  }

const DashboardRkpdHasil_evaluasiRouteRouteWithChildren =
  DashboardRkpdHasil_evaluasiRouteRoute._addFileChildren(
    DashboardRkpdHasil_evaluasiRouteRouteChildren,
  )

interface DashboardRkpdIkdRouteRouteChildren {
  DashboardRkpdIkdIndexRoute: typeof DashboardRkpdIkdIndexRoute
}

const DashboardRkpdIkdRouteRouteChildren: DashboardRkpdIkdRouteRouteChildren = {
  DashboardRkpdIkdIndexRoute: DashboardRkpdIkdIndexRoute,
}

const DashboardRkpdIkdRouteRouteWithChildren =
  DashboardRkpdIkdRouteRoute._addFileChildren(
    DashboardRkpdIkdRouteRouteChildren,
  )

interface DashboardRkpdIkuRouteRouteChildren {
  DashboardRkpdIkuIndexRoute: typeof DashboardRkpdIkuIndexRoute
}

const DashboardRkpdIkuRouteRouteChildren: DashboardRkpdIkuRouteRouteChildren = {
  DashboardRkpdIkuIndexRoute: DashboardRkpdIkuIndexRoute,
}

const DashboardRkpdIkuRouteRouteWithChildren =
  DashboardRkpdIkuRouteRoute._addFileChildren(
    DashboardRkpdIkuRouteRouteChildren,
  )

interface DashboardRkpdIku_ikdRouteRouteChildren {
  DashboardRkpdIku_ikdIkdRoute: typeof DashboardRkpdIku_ikdIkdRoute
  DashboardRkpdIku_ikdIkd_capaianRoute: typeof DashboardRkpdIku_ikdIkd_capaianRoute
  DashboardRkpdIku_ikdIkuRoute: typeof DashboardRkpdIku_ikdIkuRoute
  DashboardRkpdIku_ikdIku_capaianRoute: typeof DashboardRkpdIku_ikdIku_capaianRoute
  DashboardRkpdIku_ikdTaggingRoute: typeof DashboardRkpdIku_ikdTaggingRoute
  DashboardRkpdIku_ikdIndexRoute: typeof DashboardRkpdIku_ikdIndexRoute
}

const DashboardRkpdIku_ikdRouteRouteChildren: DashboardRkpdIku_ikdRouteRouteChildren =
  {
    DashboardRkpdIku_ikdIkdRoute: DashboardRkpdIku_ikdIkdRoute,
    DashboardRkpdIku_ikdIkd_capaianRoute: DashboardRkpdIku_ikdIkd_capaianRoute,
    DashboardRkpdIku_ikdIkuRoute: DashboardRkpdIku_ikdIkuRoute,
    DashboardRkpdIku_ikdIku_capaianRoute: DashboardRkpdIku_ikdIku_capaianRoute,
    DashboardRkpdIku_ikdTaggingRoute: DashboardRkpdIku_ikdTaggingRoute,
    DashboardRkpdIku_ikdIndexRoute: DashboardRkpdIku_ikdIndexRoute,
  }

const DashboardRkpdIku_ikdRouteRouteWithChildren =
  DashboardRkpdIku_ikdRouteRoute._addFileChildren(
    DashboardRkpdIku_ikdRouteRouteChildren,
  )

interface DashboardRkpdRenja_rkpdRouteRouteChildren {
  DashboardRkpdRenja_rkpdIndikatorRoute: typeof DashboardRkpdRenja_rkpdIndikatorRoute
  DashboardRkpdRenja_rkpdPaguRoute: typeof DashboardRkpdRenja_rkpdPaguRoute
  DashboardRkpdRenja_rkpdRealisasiRoute: typeof DashboardRkpdRenja_rkpdRealisasiRoute
  DashboardRkpdRenja_rkpdRekeningRoute: typeof DashboardRkpdRenja_rkpdRekeningRoute
  DashboardRkpdRenja_rkpdRenjaRoute: typeof DashboardRkpdRenja_rkpdRenjaRoute
  DashboardRkpdRenja_rkpdIndexRoute: typeof DashboardRkpdRenja_rkpdIndexRoute
}

const DashboardRkpdRenja_rkpdRouteRouteChildren: DashboardRkpdRenja_rkpdRouteRouteChildren =
  {
    DashboardRkpdRenja_rkpdIndikatorRoute:
      DashboardRkpdRenja_rkpdIndikatorRoute,
    DashboardRkpdRenja_rkpdPaguRoute: DashboardRkpdRenja_rkpdPaguRoute,
    DashboardRkpdRenja_rkpdRealisasiRoute:
      DashboardRkpdRenja_rkpdRealisasiRoute,
    DashboardRkpdRenja_rkpdRekeningRoute: DashboardRkpdRenja_rkpdRekeningRoute,
    DashboardRkpdRenja_rkpdRenjaRoute: DashboardRkpdRenja_rkpdRenjaRoute,
    DashboardRkpdRenja_rkpdIndexRoute: DashboardRkpdRenja_rkpdIndexRoute,
  }

const DashboardRkpdRenja_rkpdRouteRouteWithChildren =
  DashboardRkpdRenja_rkpdRouteRoute._addFileChildren(
    DashboardRkpdRenja_rkpdRouteRouteChildren,
  )

interface DashboardRkpdRenstraRouteRouteChildren {
  DashboardRkpdRenstraIokRoute: typeof DashboardRkpdRenstraIokRoute
  DashboardRkpdRenstraIopRoute: typeof DashboardRkpdRenstraIopRoute
  DashboardRkpdRenstraIoskRoute: typeof DashboardRkpdRenstraIoskRoute
  DashboardRkpdRenstraIndexRoute: typeof DashboardRkpdRenstraIndexRoute
}

const DashboardRkpdRenstraRouteRouteChildren: DashboardRkpdRenstraRouteRouteChildren =
  {
    DashboardRkpdRenstraIokRoute: DashboardRkpdRenstraIokRoute,
    DashboardRkpdRenstraIopRoute: DashboardRkpdRenstraIopRoute,
    DashboardRkpdRenstraIoskRoute: DashboardRkpdRenstraIoskRoute,
    DashboardRkpdRenstraIndexRoute: DashboardRkpdRenstraIndexRoute,
  }

const DashboardRkpdRenstraRouteRouteWithChildren =
  DashboardRkpdRenstraRouteRoute._addFileChildren(
    DashboardRkpdRenstraRouteRouteChildren,
  )

interface DashboardRkpdRenstra_rpjmdRouteRouteChildren {
  DashboardRkpdRenstra_rpjmdPagu_indikatorRoute: typeof DashboardRkpdRenstra_rpjmdPagu_indikatorRoute
  DashboardRkpdRenstra_rpjmdRealisasiRoute: typeof DashboardRkpdRenstra_rpjmdRealisasiRoute
  DashboardRkpdRenstra_rpjmdRekeningRoute: typeof DashboardRkpdRenstra_rpjmdRekeningRoute
  DashboardRkpdRenstra_rpjmdIndexRoute: typeof DashboardRkpdRenstra_rpjmdIndexRoute
}

const DashboardRkpdRenstra_rpjmdRouteRouteChildren: DashboardRkpdRenstra_rpjmdRouteRouteChildren =
  {
    DashboardRkpdRenstra_rpjmdPagu_indikatorRoute:
      DashboardRkpdRenstra_rpjmdPagu_indikatorRoute,
    DashboardRkpdRenstra_rpjmdRealisasiRoute:
      DashboardRkpdRenstra_rpjmdRealisasiRoute,
    DashboardRkpdRenstra_rpjmdRekeningRoute:
      DashboardRkpdRenstra_rpjmdRekeningRoute,
    DashboardRkpdRenstra_rpjmdIndexRoute: DashboardRkpdRenstra_rpjmdIndexRoute,
  }

const DashboardRkpdRenstra_rpjmdRouteRouteWithChildren =
  DashboardRkpdRenstra_rpjmdRouteRoute._addFileChildren(
    DashboardRkpdRenstra_rpjmdRouteRouteChildren,
  )

interface DashboardRkpdRouteRouteChildren {
  DashboardRkpdHasil_evaluasiRouteRoute: typeof DashboardRkpdHasil_evaluasiRouteRouteWithChildren
  DashboardRkpdIkdRouteRoute: typeof DashboardRkpdIkdRouteRouteWithChildren
  DashboardRkpdIkuRouteRoute: typeof DashboardRkpdIkuRouteRouteWithChildren
  DashboardRkpdIku_ikdRouteRoute: typeof DashboardRkpdIku_ikdRouteRouteWithChildren
  DashboardRkpdRenja_rkpdRouteRoute: typeof DashboardRkpdRenja_rkpdRouteRouteWithChildren
  DashboardRkpdRenstraRouteRoute: typeof DashboardRkpdRenstraRouteRouteWithChildren
  DashboardRkpdRenstra_rpjmdRouteRoute: typeof DashboardRkpdRenstra_rpjmdRouteRouteWithChildren
  DashboardRkpdCapaianRoute: typeof DashboardRkpdCapaianRoute
  DashboardRkpdIndikatorRoute: typeof DashboardRkpdIndikatorRoute
  DashboardRkpdPagu_indikatifRoute: typeof DashboardRkpdPagu_indikatifRoute
  DashboardRkpdIndexRoute: typeof DashboardRkpdIndexRoute
}

const DashboardRkpdRouteRouteChildren: DashboardRkpdRouteRouteChildren = {
  DashboardRkpdHasil_evaluasiRouteRoute:
    DashboardRkpdHasil_evaluasiRouteRouteWithChildren,
  DashboardRkpdIkdRouteRoute: DashboardRkpdIkdRouteRouteWithChildren,
  DashboardRkpdIkuRouteRoute: DashboardRkpdIkuRouteRouteWithChildren,
  DashboardRkpdIku_ikdRouteRoute: DashboardRkpdIku_ikdRouteRouteWithChildren,
  DashboardRkpdRenja_rkpdRouteRoute:
    DashboardRkpdRenja_rkpdRouteRouteWithChildren,
  DashboardRkpdRenstraRouteRoute: DashboardRkpdRenstraRouteRouteWithChildren,
  DashboardRkpdRenstra_rpjmdRouteRoute:
    DashboardRkpdRenstra_rpjmdRouteRouteWithChildren,
  DashboardRkpdCapaianRoute: DashboardRkpdCapaianRoute,
  DashboardRkpdIndikatorRoute: DashboardRkpdIndikatorRoute,
  DashboardRkpdPagu_indikatifRoute: DashboardRkpdPagu_indikatifRoute,
  DashboardRkpdIndexRoute: DashboardRkpdIndexRoute,
}

const DashboardRkpdRouteRouteWithChildren =
  DashboardRkpdRouteRoute._addFileChildren(DashboardRkpdRouteRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardDakRouteRoute: typeof DashboardDakRouteRouteWithChildren
  DashboardKonfigurasiRouteRoute: typeof DashboardKonfigurasiRouteRouteWithChildren
  DashboardRkpdRouteRoute: typeof DashboardRkpdRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardDakRouteRoute: DashboardDakRouteRouteWithChildren,
  DashboardKonfigurasiRouteRoute: DashboardKonfigurasiRouteRouteWithChildren,
  DashboardRkpdRouteRoute: DashboardRkpdRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLogoutRoute: AuthLogoutRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
