/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as DashboardRkpdRouteRouteImport } from './routes/_dashboard/rkpd/route'
import { Route as DashboardMasterRouteRouteImport } from './routes/_dashboard/master/route'
import { Route as DashboardKonfigurasiRouteRouteImport } from './routes/_dashboard/konfigurasi/route'
import { Route as DashboardDakRouteRouteImport } from './routes/_dashboard/dak/route'
import { Route as DashboardRkpdIndexRouteImport } from './routes/_dashboard/rkpd/index'
import { Route as DashboardMasterIndexRouteImport } from './routes/_dashboard/master/index'
import { Route as DashboardKonfigurasiIndexRouteImport } from './routes/_dashboard/konfigurasi/index'
import { Route as DashboardDakIndexRouteImport } from './routes/_dashboard/dak/index'
import { Route as DashboardRkpdRenjaRouteImport } from './routes/_dashboard/rkpd/renja'
import { Route as DashboardRkpdRealisasiRouteImport } from './routes/_dashboard/rkpd/realisasi'
import { Route as DashboardRkpdPagu_indikatifRouteImport } from './routes/_dashboard/rkpd/pagu_indikatif'
import { Route as DashboardMasterSkpdRouteImport } from './routes/_dashboard/master/skpd'
import { Route as DashboardMasterRoleRouteImport } from './routes/_dashboard/master/role'
import { Route as DashboardMasterRekeningRouteImport } from './routes/_dashboard/master/rekening'
import { Route as DashboardMasterPeriodeRouteImport } from './routes/_dashboard/master/periode'
import { Route as DashboardMasterOrganisasiRouteImport } from './routes/_dashboard/master/organisasi'
import { Route as DashboardMasterJadwalRouteImport } from './routes/_dashboard/master/jadwal'
import { Route as DashboardKonfigurasiUserRouteImport } from './routes/_dashboard/konfigurasi/user'
import { Route as DashboardKonfigurasiTransferdataRouteImport } from './routes/_dashboard/konfigurasi/transferdata'
import { Route as DashboardDakDaftardakRouteImport } from './routes/_dashboard/dak/daftardak'
import { Route as DashboardRkpdRenstraRouteRouteImport } from './routes/_dashboard/rkpd/renstra/route'
import { Route as DashboardRkpdIkuRouteRouteImport } from './routes/_dashboard/rkpd/iku/route'
import { Route as DashboardDakKabupatenRouteRouteImport } from './routes/_dashboard/dak/kabupaten/route'
import { Route as DashboardRkpdRenstraIndexRouteImport } from './routes/_dashboard/rkpd/renstra/index'
import { Route as DashboardRkpdIkuIndexRouteImport } from './routes/_dashboard/rkpd/iku/index'
import { Route as DashboardDakKabupatenIndexRouteImport } from './routes/_dashboard/dak/kabupaten/index'
import { Route as DashboardRkpdRenstraIoskRouteImport } from './routes/_dashboard/rkpd/renstra/iosk'
import { Route as DashboardRkpdRenstraIopRouteImport } from './routes/_dashboard/rkpd/renstra/iop'
import { Route as DashboardRkpdRenstraIokRouteImport } from './routes/_dashboard/rkpd/renstra/iok'
import { Route as DashboardRkpdIkuIku_taggingRouteImport } from './routes/_dashboard/rkpd/iku/iku_tagging'
import { Route as DashboardRkpdIkuIku_listRouteImport } from './routes/_dashboard/rkpd/iku/iku_list'
import { Route as DashboardRkpdIkuIku_capaianRouteImport } from './routes/_dashboard/rkpd/iku/iku_capaian'
import { Route as DashboardDakKabupatenMonitoringRouteImport } from './routes/_dashboard/dak/kabupaten/monitoring'
import { Route as DashboardDakKabupatenIdentifikasiRouteImport } from './routes/_dashboard/dak/kabupaten/identifikasi'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardRkpdRouteRoute = DashboardRkpdRouteRouteImport.update({
  id: '/rkpd',
  path: '/rkpd',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMasterRouteRoute = DashboardMasterRouteRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardKonfigurasiRouteRoute =
  DashboardKonfigurasiRouteRouteImport.update({
    id: '/konfigurasi',
    path: '/konfigurasi',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardDakRouteRoute = DashboardDakRouteRouteImport.update({
  id: '/dak',
  path: '/dak',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRkpdIndexRoute = DashboardRkpdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRkpdRouteRoute,
} as any)
const DashboardMasterIndexRoute = DashboardMasterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardMasterRouteRoute,
} as any)
const DashboardKonfigurasiIndexRoute =
  DashboardKonfigurasiIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardKonfigurasiRouteRoute,
  } as any)
const DashboardDakIndexRoute = DashboardDakIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardDakRouteRoute,
} as any)
const DashboardRkpdRenjaRoute = DashboardRkpdRenjaRouteImport.update({
  id: '/renja',
  path: '/renja',
  getParentRoute: () => DashboardRkpdRouteRoute,
} as any)
const DashboardRkpdRealisasiRoute = DashboardRkpdRealisasiRouteImport.update({
  id: '/realisasi',
  path: '/realisasi',
  getParentRoute: () => DashboardRkpdRouteRoute,
} as any)
const DashboardRkpdPagu_indikatifRoute =
  DashboardRkpdPagu_indikatifRouteImport.update({
    id: '/pagu_indikatif',
    path: '/pagu_indikatif',
    getParentRoute: () => DashboardRkpdRouteRoute,
  } as any)
const DashboardMasterSkpdRoute = DashboardMasterSkpdRouteImport.update({
  id: '/skpd',
  path: '/skpd',
  getParentRoute: () => DashboardMasterRouteRoute,
} as any)
const DashboardMasterRoleRoute = DashboardMasterRoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => DashboardMasterRouteRoute,
} as any)
const DashboardMasterRekeningRoute = DashboardMasterRekeningRouteImport.update({
  id: '/rekening',
  path: '/rekening',
  getParentRoute: () => DashboardMasterRouteRoute,
} as any)
const DashboardMasterPeriodeRoute = DashboardMasterPeriodeRouteImport.update({
  id: '/periode',
  path: '/periode',
  getParentRoute: () => DashboardMasterRouteRoute,
} as any)
const DashboardMasterOrganisasiRoute =
  DashboardMasterOrganisasiRouteImport.update({
    id: '/organisasi',
    path: '/organisasi',
    getParentRoute: () => DashboardMasterRouteRoute,
  } as any)
const DashboardMasterJadwalRoute = DashboardMasterJadwalRouteImport.update({
  id: '/jadwal',
  path: '/jadwal',
  getParentRoute: () => DashboardMasterRouteRoute,
} as any)
const DashboardKonfigurasiUserRoute =
  DashboardKonfigurasiUserRouteImport.update({
    id: '/user',
    path: '/user',
    getParentRoute: () => DashboardKonfigurasiRouteRoute,
  } as any)
const DashboardKonfigurasiTransferdataRoute =
  DashboardKonfigurasiTransferdataRouteImport.update({
    id: '/transferdata',
    path: '/transferdata',
    getParentRoute: () => DashboardKonfigurasiRouteRoute,
  } as any)
const DashboardDakDaftardakRoute = DashboardDakDaftardakRouteImport.update({
  id: '/daftardak',
  path: '/daftardak',
  getParentRoute: () => DashboardDakRouteRoute,
} as any)
const DashboardRkpdRenstraRouteRoute =
  DashboardRkpdRenstraRouteRouteImport.update({
    id: '/renstra',
    path: '/renstra',
    getParentRoute: () => DashboardRkpdRouteRoute,
  } as any)
const DashboardRkpdIkuRouteRoute = DashboardRkpdIkuRouteRouteImport.update({
  id: '/iku',
  path: '/iku',
  getParentRoute: () => DashboardRkpdRouteRoute,
} as any)
const DashboardDakKabupatenRouteRoute =
  DashboardDakKabupatenRouteRouteImport.update({
    id: '/kabupaten',
    path: '/kabupaten',
    getParentRoute: () => DashboardDakRouteRoute,
  } as any)
const DashboardRkpdRenstraIndexRoute =
  DashboardRkpdRenstraIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardRkpdRenstraRouteRoute,
  } as any)
const DashboardRkpdIkuIndexRoute = DashboardRkpdIkuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRkpdIkuRouteRoute,
} as any)
const DashboardDakKabupatenIndexRoute =
  DashboardDakKabupatenIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardDakKabupatenRouteRoute,
  } as any)
const DashboardRkpdRenstraIoskRoute =
  DashboardRkpdRenstraIoskRouteImport.update({
    id: '/iosk',
    path: '/iosk',
    getParentRoute: () => DashboardRkpdRenstraRouteRoute,
  } as any)
const DashboardRkpdRenstraIopRoute = DashboardRkpdRenstraIopRouteImport.update({
  id: '/iop',
  path: '/iop',
  getParentRoute: () => DashboardRkpdRenstraRouteRoute,
} as any)
const DashboardRkpdRenstraIokRoute = DashboardRkpdRenstraIokRouteImport.update({
  id: '/iok',
  path: '/iok',
  getParentRoute: () => DashboardRkpdRenstraRouteRoute,
} as any)
const DashboardRkpdIkuIku_taggingRoute =
  DashboardRkpdIkuIku_taggingRouteImport.update({
    id: '/iku_tagging',
    path: '/iku_tagging',
    getParentRoute: () => DashboardRkpdIkuRouteRoute,
  } as any)
const DashboardRkpdIkuIku_listRoute =
  DashboardRkpdIkuIku_listRouteImport.update({
    id: '/iku_list',
    path: '/iku_list',
    getParentRoute: () => DashboardRkpdIkuRouteRoute,
  } as any)
const DashboardRkpdIkuIku_capaianRoute =
  DashboardRkpdIkuIku_capaianRouteImport.update({
    id: '/iku_capaian',
    path: '/iku_capaian',
    getParentRoute: () => DashboardRkpdIkuRouteRoute,
  } as any)
const DashboardDakKabupatenMonitoringRoute =
  DashboardDakKabupatenMonitoringRouteImport.update({
    id: '/monitoring',
    path: '/monitoring',
    getParentRoute: () => DashboardDakKabupatenRouteRoute,
  } as any)
const DashboardDakKabupatenIdentifikasiRoute =
  DashboardDakKabupatenIdentifikasiRouteImport.update({
    id: '/identifikasi',
    path: '/identifikasi',
    getParentRoute: () => DashboardDakKabupatenRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteRouteWithChildren
  '/dak': typeof DashboardDakRouteRouteWithChildren
  '/konfigurasi': typeof DashboardKonfigurasiRouteRouteWithChildren
  '/master': typeof DashboardMasterRouteRouteWithChildren
  '/rkpd': typeof DashboardRkpdRouteRouteWithChildren
  '/auth/logout': typeof AuthLogoutRoute
  '/': typeof DashboardIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/dak/kabupaten': typeof DashboardDakKabupatenRouteRouteWithChildren
  '/rkpd/iku': typeof DashboardRkpdIkuRouteRouteWithChildren
  '/rkpd/renstra': typeof DashboardRkpdRenstraRouteRouteWithChildren
  '/dak/daftardak': typeof DashboardDakDaftardakRoute
  '/konfigurasi/transferdata': typeof DashboardKonfigurasiTransferdataRoute
  '/konfigurasi/user': typeof DashboardKonfigurasiUserRoute
  '/master/jadwal': typeof DashboardMasterJadwalRoute
  '/master/organisasi': typeof DashboardMasterOrganisasiRoute
  '/master/periode': typeof DashboardMasterPeriodeRoute
  '/master/rekening': typeof DashboardMasterRekeningRoute
  '/master/role': typeof DashboardMasterRoleRoute
  '/master/skpd': typeof DashboardMasterSkpdRoute
  '/rkpd/pagu_indikatif': typeof DashboardRkpdPagu_indikatifRoute
  '/rkpd/realisasi': typeof DashboardRkpdRealisasiRoute
  '/rkpd/renja': typeof DashboardRkpdRenjaRoute
  '/dak/': typeof DashboardDakIndexRoute
  '/konfigurasi/': typeof DashboardKonfigurasiIndexRoute
  '/master/': typeof DashboardMasterIndexRoute
  '/rkpd/': typeof DashboardRkpdIndexRoute
  '/dak/kabupaten/identifikasi': typeof DashboardDakKabupatenIdentifikasiRoute
  '/dak/kabupaten/monitoring': typeof DashboardDakKabupatenMonitoringRoute
  '/rkpd/iku/iku_capaian': typeof DashboardRkpdIkuIku_capaianRoute
  '/rkpd/iku/iku_list': typeof DashboardRkpdIkuIku_listRoute
  '/rkpd/iku/iku_tagging': typeof DashboardRkpdIkuIku_taggingRoute
  '/rkpd/renstra/iok': typeof DashboardRkpdRenstraIokRoute
  '/rkpd/renstra/iop': typeof DashboardRkpdRenstraIopRoute
  '/rkpd/renstra/iosk': typeof DashboardRkpdRenstraIoskRoute
  '/dak/kabupaten/': typeof DashboardDakKabupatenIndexRoute
  '/rkpd/iku/': typeof DashboardRkpdIkuIndexRoute
  '/rkpd/renstra/': typeof DashboardRkpdRenstraIndexRoute
}
export interface FileRoutesByTo {
  '/auth/logout': typeof AuthLogoutRoute
  '/': typeof DashboardIndexRoute
  '/auth': typeof AuthIndexRoute
  '/dak/daftardak': typeof DashboardDakDaftardakRoute
  '/konfigurasi/transferdata': typeof DashboardKonfigurasiTransferdataRoute
  '/konfigurasi/user': typeof DashboardKonfigurasiUserRoute
  '/master/jadwal': typeof DashboardMasterJadwalRoute
  '/master/organisasi': typeof DashboardMasterOrganisasiRoute
  '/master/periode': typeof DashboardMasterPeriodeRoute
  '/master/rekening': typeof DashboardMasterRekeningRoute
  '/master/role': typeof DashboardMasterRoleRoute
  '/master/skpd': typeof DashboardMasterSkpdRoute
  '/rkpd/pagu_indikatif': typeof DashboardRkpdPagu_indikatifRoute
  '/rkpd/realisasi': typeof DashboardRkpdRealisasiRoute
  '/rkpd/renja': typeof DashboardRkpdRenjaRoute
  '/dak': typeof DashboardDakIndexRoute
  '/konfigurasi': typeof DashboardKonfigurasiIndexRoute
  '/master': typeof DashboardMasterIndexRoute
  '/rkpd': typeof DashboardRkpdIndexRoute
  '/dak/kabupaten/identifikasi': typeof DashboardDakKabupatenIdentifikasiRoute
  '/dak/kabupaten/monitoring': typeof DashboardDakKabupatenMonitoringRoute
  '/rkpd/iku/iku_capaian': typeof DashboardRkpdIkuIku_capaianRoute
  '/rkpd/iku/iku_list': typeof DashboardRkpdIkuIku_listRoute
  '/rkpd/iku/iku_tagging': typeof DashboardRkpdIkuIku_taggingRoute
  '/rkpd/renstra/iok': typeof DashboardRkpdRenstraIokRoute
  '/rkpd/renstra/iop': typeof DashboardRkpdRenstraIopRoute
  '/rkpd/renstra/iosk': typeof DashboardRkpdRenstraIoskRoute
  '/dak/kabupaten': typeof DashboardDakKabupatenIndexRoute
  '/rkpd/iku': typeof DashboardRkpdIkuIndexRoute
  '/rkpd/renstra': typeof DashboardRkpdRenstraIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/_dashboard/dak': typeof DashboardDakRouteRouteWithChildren
  '/_dashboard/konfigurasi': typeof DashboardKonfigurasiRouteRouteWithChildren
  '/_dashboard/master': typeof DashboardMasterRouteRouteWithChildren
  '/_dashboard/rkpd': typeof DashboardRkpdRouteRouteWithChildren
  '/auth/logout': typeof AuthLogoutRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_dashboard/dak/kabupaten': typeof DashboardDakKabupatenRouteRouteWithChildren
  '/_dashboard/rkpd/iku': typeof DashboardRkpdIkuRouteRouteWithChildren
  '/_dashboard/rkpd/renstra': typeof DashboardRkpdRenstraRouteRouteWithChildren
  '/_dashboard/dak/daftardak': typeof DashboardDakDaftardakRoute
  '/_dashboard/konfigurasi/transferdata': typeof DashboardKonfigurasiTransferdataRoute
  '/_dashboard/konfigurasi/user': typeof DashboardKonfigurasiUserRoute
  '/_dashboard/master/jadwal': typeof DashboardMasterJadwalRoute
  '/_dashboard/master/organisasi': typeof DashboardMasterOrganisasiRoute
  '/_dashboard/master/periode': typeof DashboardMasterPeriodeRoute
  '/_dashboard/master/rekening': typeof DashboardMasterRekeningRoute
  '/_dashboard/master/role': typeof DashboardMasterRoleRoute
  '/_dashboard/master/skpd': typeof DashboardMasterSkpdRoute
  '/_dashboard/rkpd/pagu_indikatif': typeof DashboardRkpdPagu_indikatifRoute
  '/_dashboard/rkpd/realisasi': typeof DashboardRkpdRealisasiRoute
  '/_dashboard/rkpd/renja': typeof DashboardRkpdRenjaRoute
  '/_dashboard/dak/': typeof DashboardDakIndexRoute
  '/_dashboard/konfigurasi/': typeof DashboardKonfigurasiIndexRoute
  '/_dashboard/master/': typeof DashboardMasterIndexRoute
  '/_dashboard/rkpd/': typeof DashboardRkpdIndexRoute
  '/_dashboard/dak/kabupaten/identifikasi': typeof DashboardDakKabupatenIdentifikasiRoute
  '/_dashboard/dak/kabupaten/monitoring': typeof DashboardDakKabupatenMonitoringRoute
  '/_dashboard/rkpd/iku/iku_capaian': typeof DashboardRkpdIkuIku_capaianRoute
  '/_dashboard/rkpd/iku/iku_list': typeof DashboardRkpdIkuIku_listRoute
  '/_dashboard/rkpd/iku/iku_tagging': typeof DashboardRkpdIkuIku_taggingRoute
  '/_dashboard/rkpd/renstra/iok': typeof DashboardRkpdRenstraIokRoute
  '/_dashboard/rkpd/renstra/iop': typeof DashboardRkpdRenstraIopRoute
  '/_dashboard/rkpd/renstra/iosk': typeof DashboardRkpdRenstraIoskRoute
  '/_dashboard/dak/kabupaten/': typeof DashboardDakKabupatenIndexRoute
  '/_dashboard/rkpd/iku/': typeof DashboardRkpdIkuIndexRoute
  '/_dashboard/rkpd/renstra/': typeof DashboardRkpdRenstraIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/dak'
    | '/konfigurasi'
    | '/master'
    | '/rkpd'
    | '/auth/logout'
    | '/'
    | '/auth/'
    | '/dak/kabupaten'
    | '/rkpd/iku'
    | '/rkpd/renstra'
    | '/dak/daftardak'
    | '/konfigurasi/transferdata'
    | '/konfigurasi/user'
    | '/master/jadwal'
    | '/master/organisasi'
    | '/master/periode'
    | '/master/rekening'
    | '/master/role'
    | '/master/skpd'
    | '/rkpd/pagu_indikatif'
    | '/rkpd/realisasi'
    | '/rkpd/renja'
    | '/dak/'
    | '/konfigurasi/'
    | '/master/'
    | '/rkpd/'
    | '/dak/kabupaten/identifikasi'
    | '/dak/kabupaten/monitoring'
    | '/rkpd/iku/iku_capaian'
    | '/rkpd/iku/iku_list'
    | '/rkpd/iku/iku_tagging'
    | '/rkpd/renstra/iok'
    | '/rkpd/renstra/iop'
    | '/rkpd/renstra/iosk'
    | '/dak/kabupaten/'
    | '/rkpd/iku/'
    | '/rkpd/renstra/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/logout'
    | '/'
    | '/auth'
    | '/dak/daftardak'
    | '/konfigurasi/transferdata'
    | '/konfigurasi/user'
    | '/master/jadwal'
    | '/master/organisasi'
    | '/master/periode'
    | '/master/rekening'
    | '/master/role'
    | '/master/skpd'
    | '/rkpd/pagu_indikatif'
    | '/rkpd/realisasi'
    | '/rkpd/renja'
    | '/dak'
    | '/konfigurasi'
    | '/master'
    | '/rkpd'
    | '/dak/kabupaten/identifikasi'
    | '/dak/kabupaten/monitoring'
    | '/rkpd/iku/iku_capaian'
    | '/rkpd/iku/iku_list'
    | '/rkpd/iku/iku_tagging'
    | '/rkpd/renstra/iok'
    | '/rkpd/renstra/iop'
    | '/rkpd/renstra/iosk'
    | '/dak/kabupaten'
    | '/rkpd/iku'
    | '/rkpd/renstra'
  id:
    | '__root__'
    | '/_dashboard'
    | '/auth'
    | '/_dashboard/dak'
    | '/_dashboard/konfigurasi'
    | '/_dashboard/master'
    | '/_dashboard/rkpd'
    | '/auth/logout'
    | '/_dashboard/'
    | '/auth/'
    | '/_dashboard/dak/kabupaten'
    | '/_dashboard/rkpd/iku'
    | '/_dashboard/rkpd/renstra'
    | '/_dashboard/dak/daftardak'
    | '/_dashboard/konfigurasi/transferdata'
    | '/_dashboard/konfigurasi/user'
    | '/_dashboard/master/jadwal'
    | '/_dashboard/master/organisasi'
    | '/_dashboard/master/periode'
    | '/_dashboard/master/rekening'
    | '/_dashboard/master/role'
    | '/_dashboard/master/skpd'
    | '/_dashboard/rkpd/pagu_indikatif'
    | '/_dashboard/rkpd/realisasi'
    | '/_dashboard/rkpd/renja'
    | '/_dashboard/dak/'
    | '/_dashboard/konfigurasi/'
    | '/_dashboard/master/'
    | '/_dashboard/rkpd/'
    | '/_dashboard/dak/kabupaten/identifikasi'
    | '/_dashboard/dak/kabupaten/monitoring'
    | '/_dashboard/rkpd/iku/iku_capaian'
    | '/_dashboard/rkpd/iku/iku_list'
    | '/_dashboard/rkpd/iku/iku_tagging'
    | '/_dashboard/rkpd/renstra/iok'
    | '/_dashboard/rkpd/renstra/iop'
    | '/_dashboard/rkpd/renstra/iosk'
    | '/_dashboard/dak/kabupaten/'
    | '/_dashboard/rkpd/iku/'
    | '/_dashboard/rkpd/renstra/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_dashboard/rkpd': {
      id: '/_dashboard/rkpd'
      path: '/rkpd'
      fullPath: '/rkpd'
      preLoaderRoute: typeof DashboardRkpdRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/master': {
      id: '/_dashboard/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof DashboardMasterRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/konfigurasi': {
      id: '/_dashboard/konfigurasi'
      path: '/konfigurasi'
      fullPath: '/konfigurasi'
      preLoaderRoute: typeof DashboardKonfigurasiRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/dak': {
      id: '/_dashboard/dak'
      path: '/dak'
      fullPath: '/dak'
      preLoaderRoute: typeof DashboardDakRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/rkpd/': {
      id: '/_dashboard/rkpd/'
      path: '/'
      fullPath: '/rkpd/'
      preLoaderRoute: typeof DashboardRkpdIndexRouteImport
      parentRoute: typeof DashboardRkpdRouteRoute
    }
    '/_dashboard/master/': {
      id: '/_dashboard/master/'
      path: '/'
      fullPath: '/master/'
      preLoaderRoute: typeof DashboardMasterIndexRouteImport
      parentRoute: typeof DashboardMasterRouteRoute
    }
    '/_dashboard/konfigurasi/': {
      id: '/_dashboard/konfigurasi/'
      path: '/'
      fullPath: '/konfigurasi/'
      preLoaderRoute: typeof DashboardKonfigurasiIndexRouteImport
      parentRoute: typeof DashboardKonfigurasiRouteRoute
    }
    '/_dashboard/dak/': {
      id: '/_dashboard/dak/'
      path: '/'
      fullPath: '/dak/'
      preLoaderRoute: typeof DashboardDakIndexRouteImport
      parentRoute: typeof DashboardDakRouteRoute
    }
    '/_dashboard/rkpd/renja': {
      id: '/_dashboard/rkpd/renja'
      path: '/renja'
      fullPath: '/rkpd/renja'
      preLoaderRoute: typeof DashboardRkpdRenjaRouteImport
      parentRoute: typeof DashboardRkpdRouteRoute
    }
    '/_dashboard/rkpd/realisasi': {
      id: '/_dashboard/rkpd/realisasi'
      path: '/realisasi'
      fullPath: '/rkpd/realisasi'
      preLoaderRoute: typeof DashboardRkpdRealisasiRouteImport
      parentRoute: typeof DashboardRkpdRouteRoute
    }
    '/_dashboard/rkpd/pagu_indikatif': {
      id: '/_dashboard/rkpd/pagu_indikatif'
      path: '/pagu_indikatif'
      fullPath: '/rkpd/pagu_indikatif'
      preLoaderRoute: typeof DashboardRkpdPagu_indikatifRouteImport
      parentRoute: typeof DashboardRkpdRouteRoute
    }
    '/_dashboard/master/skpd': {
      id: '/_dashboard/master/skpd'
      path: '/skpd'
      fullPath: '/master/skpd'
      preLoaderRoute: typeof DashboardMasterSkpdRouteImport
      parentRoute: typeof DashboardMasterRouteRoute
    }
    '/_dashboard/master/role': {
      id: '/_dashboard/master/role'
      path: '/role'
      fullPath: '/master/role'
      preLoaderRoute: typeof DashboardMasterRoleRouteImport
      parentRoute: typeof DashboardMasterRouteRoute
    }
    '/_dashboard/master/rekening': {
      id: '/_dashboard/master/rekening'
      path: '/rekening'
      fullPath: '/master/rekening'
      preLoaderRoute: typeof DashboardMasterRekeningRouteImport
      parentRoute: typeof DashboardMasterRouteRoute
    }
    '/_dashboard/master/periode': {
      id: '/_dashboard/master/periode'
      path: '/periode'
      fullPath: '/master/periode'
      preLoaderRoute: typeof DashboardMasterPeriodeRouteImport
      parentRoute: typeof DashboardMasterRouteRoute
    }
    '/_dashboard/master/organisasi': {
      id: '/_dashboard/master/organisasi'
      path: '/organisasi'
      fullPath: '/master/organisasi'
      preLoaderRoute: typeof DashboardMasterOrganisasiRouteImport
      parentRoute: typeof DashboardMasterRouteRoute
    }
    '/_dashboard/master/jadwal': {
      id: '/_dashboard/master/jadwal'
      path: '/jadwal'
      fullPath: '/master/jadwal'
      preLoaderRoute: typeof DashboardMasterJadwalRouteImport
      parentRoute: typeof DashboardMasterRouteRoute
    }
    '/_dashboard/konfigurasi/user': {
      id: '/_dashboard/konfigurasi/user'
      path: '/user'
      fullPath: '/konfigurasi/user'
      preLoaderRoute: typeof DashboardKonfigurasiUserRouteImport
      parentRoute: typeof DashboardKonfigurasiRouteRoute
    }
    '/_dashboard/konfigurasi/transferdata': {
      id: '/_dashboard/konfigurasi/transferdata'
      path: '/transferdata'
      fullPath: '/konfigurasi/transferdata'
      preLoaderRoute: typeof DashboardKonfigurasiTransferdataRouteImport
      parentRoute: typeof DashboardKonfigurasiRouteRoute
    }
    '/_dashboard/dak/daftardak': {
      id: '/_dashboard/dak/daftardak'
      path: '/daftardak'
      fullPath: '/dak/daftardak'
      preLoaderRoute: typeof DashboardDakDaftardakRouteImport
      parentRoute: typeof DashboardDakRouteRoute
    }
    '/_dashboard/rkpd/renstra': {
      id: '/_dashboard/rkpd/renstra'
      path: '/renstra'
      fullPath: '/rkpd/renstra'
      preLoaderRoute: typeof DashboardRkpdRenstraRouteRouteImport
      parentRoute: typeof DashboardRkpdRouteRoute
    }
    '/_dashboard/rkpd/iku': {
      id: '/_dashboard/rkpd/iku'
      path: '/iku'
      fullPath: '/rkpd/iku'
      preLoaderRoute: typeof DashboardRkpdIkuRouteRouteImport
      parentRoute: typeof DashboardRkpdRouteRoute
    }
    '/_dashboard/dak/kabupaten': {
      id: '/_dashboard/dak/kabupaten'
      path: '/kabupaten'
      fullPath: '/dak/kabupaten'
      preLoaderRoute: typeof DashboardDakKabupatenRouteRouteImport
      parentRoute: typeof DashboardDakRouteRoute
    }
    '/_dashboard/rkpd/renstra/': {
      id: '/_dashboard/rkpd/renstra/'
      path: '/'
      fullPath: '/rkpd/renstra/'
      preLoaderRoute: typeof DashboardRkpdRenstraIndexRouteImport
      parentRoute: typeof DashboardRkpdRenstraRouteRoute
    }
    '/_dashboard/rkpd/iku/': {
      id: '/_dashboard/rkpd/iku/'
      path: '/'
      fullPath: '/rkpd/iku/'
      preLoaderRoute: typeof DashboardRkpdIkuIndexRouteImport
      parentRoute: typeof DashboardRkpdIkuRouteRoute
    }
    '/_dashboard/dak/kabupaten/': {
      id: '/_dashboard/dak/kabupaten/'
      path: '/'
      fullPath: '/dak/kabupaten/'
      preLoaderRoute: typeof DashboardDakKabupatenIndexRouteImport
      parentRoute: typeof DashboardDakKabupatenRouteRoute
    }
    '/_dashboard/rkpd/renstra/iosk': {
      id: '/_dashboard/rkpd/renstra/iosk'
      path: '/iosk'
      fullPath: '/rkpd/renstra/iosk'
      preLoaderRoute: typeof DashboardRkpdRenstraIoskRouteImport
      parentRoute: typeof DashboardRkpdRenstraRouteRoute
    }
    '/_dashboard/rkpd/renstra/iop': {
      id: '/_dashboard/rkpd/renstra/iop'
      path: '/iop'
      fullPath: '/rkpd/renstra/iop'
      preLoaderRoute: typeof DashboardRkpdRenstraIopRouteImport
      parentRoute: typeof DashboardRkpdRenstraRouteRoute
    }
    '/_dashboard/rkpd/renstra/iok': {
      id: '/_dashboard/rkpd/renstra/iok'
      path: '/iok'
      fullPath: '/rkpd/renstra/iok'
      preLoaderRoute: typeof DashboardRkpdRenstraIokRouteImport
      parentRoute: typeof DashboardRkpdRenstraRouteRoute
    }
    '/_dashboard/rkpd/iku/iku_tagging': {
      id: '/_dashboard/rkpd/iku/iku_tagging'
      path: '/iku_tagging'
      fullPath: '/rkpd/iku/iku_tagging'
      preLoaderRoute: typeof DashboardRkpdIkuIku_taggingRouteImport
      parentRoute: typeof DashboardRkpdIkuRouteRoute
    }
    '/_dashboard/rkpd/iku/iku_list': {
      id: '/_dashboard/rkpd/iku/iku_list'
      path: '/iku_list'
      fullPath: '/rkpd/iku/iku_list'
      preLoaderRoute: typeof DashboardRkpdIkuIku_listRouteImport
      parentRoute: typeof DashboardRkpdIkuRouteRoute
    }
    '/_dashboard/rkpd/iku/iku_capaian': {
      id: '/_dashboard/rkpd/iku/iku_capaian'
      path: '/iku_capaian'
      fullPath: '/rkpd/iku/iku_capaian'
      preLoaderRoute: typeof DashboardRkpdIkuIku_capaianRouteImport
      parentRoute: typeof DashboardRkpdIkuRouteRoute
    }
    '/_dashboard/dak/kabupaten/monitoring': {
      id: '/_dashboard/dak/kabupaten/monitoring'
      path: '/monitoring'
      fullPath: '/dak/kabupaten/monitoring'
      preLoaderRoute: typeof DashboardDakKabupatenMonitoringRouteImport
      parentRoute: typeof DashboardDakKabupatenRouteRoute
    }
    '/_dashboard/dak/kabupaten/identifikasi': {
      id: '/_dashboard/dak/kabupaten/identifikasi'
      path: '/identifikasi'
      fullPath: '/dak/kabupaten/identifikasi'
      preLoaderRoute: typeof DashboardDakKabupatenIdentifikasiRouteImport
      parentRoute: typeof DashboardDakKabupatenRouteRoute
    }
  }
}

interface DashboardDakKabupatenRouteRouteChildren {
  DashboardDakKabupatenIdentifikasiRoute: typeof DashboardDakKabupatenIdentifikasiRoute
  DashboardDakKabupatenMonitoringRoute: typeof DashboardDakKabupatenMonitoringRoute
  DashboardDakKabupatenIndexRoute: typeof DashboardDakKabupatenIndexRoute
}

const DashboardDakKabupatenRouteRouteChildren: DashboardDakKabupatenRouteRouteChildren =
  {
    DashboardDakKabupatenIdentifikasiRoute:
      DashboardDakKabupatenIdentifikasiRoute,
    DashboardDakKabupatenMonitoringRoute: DashboardDakKabupatenMonitoringRoute,
    DashboardDakKabupatenIndexRoute: DashboardDakKabupatenIndexRoute,
  }

const DashboardDakKabupatenRouteRouteWithChildren =
  DashboardDakKabupatenRouteRoute._addFileChildren(
    DashboardDakKabupatenRouteRouteChildren,
  )

interface DashboardDakRouteRouteChildren {
  DashboardDakKabupatenRouteRoute: typeof DashboardDakKabupatenRouteRouteWithChildren
  DashboardDakDaftardakRoute: typeof DashboardDakDaftardakRoute
  DashboardDakIndexRoute: typeof DashboardDakIndexRoute
}

const DashboardDakRouteRouteChildren: DashboardDakRouteRouteChildren = {
  DashboardDakKabupatenRouteRoute: DashboardDakKabupatenRouteRouteWithChildren,
  DashboardDakDaftardakRoute: DashboardDakDaftardakRoute,
  DashboardDakIndexRoute: DashboardDakIndexRoute,
}

const DashboardDakRouteRouteWithChildren =
  DashboardDakRouteRoute._addFileChildren(DashboardDakRouteRouteChildren)

interface DashboardKonfigurasiRouteRouteChildren {
  DashboardKonfigurasiTransferdataRoute: typeof DashboardKonfigurasiTransferdataRoute
  DashboardKonfigurasiUserRoute: typeof DashboardKonfigurasiUserRoute
  DashboardKonfigurasiIndexRoute: typeof DashboardKonfigurasiIndexRoute
}

const DashboardKonfigurasiRouteRouteChildren: DashboardKonfigurasiRouteRouteChildren =
  {
    DashboardKonfigurasiTransferdataRoute:
      DashboardKonfigurasiTransferdataRoute,
    DashboardKonfigurasiUserRoute: DashboardKonfigurasiUserRoute,
    DashboardKonfigurasiIndexRoute: DashboardKonfigurasiIndexRoute,
  }

const DashboardKonfigurasiRouteRouteWithChildren =
  DashboardKonfigurasiRouteRoute._addFileChildren(
    DashboardKonfigurasiRouteRouteChildren,
  )

interface DashboardMasterRouteRouteChildren {
  DashboardMasterJadwalRoute: typeof DashboardMasterJadwalRoute
  DashboardMasterOrganisasiRoute: typeof DashboardMasterOrganisasiRoute
  DashboardMasterPeriodeRoute: typeof DashboardMasterPeriodeRoute
  DashboardMasterRekeningRoute: typeof DashboardMasterRekeningRoute
  DashboardMasterRoleRoute: typeof DashboardMasterRoleRoute
  DashboardMasterSkpdRoute: typeof DashboardMasterSkpdRoute
  DashboardMasterIndexRoute: typeof DashboardMasterIndexRoute
}

const DashboardMasterRouteRouteChildren: DashboardMasterRouteRouteChildren = {
  DashboardMasterJadwalRoute: DashboardMasterJadwalRoute,
  DashboardMasterOrganisasiRoute: DashboardMasterOrganisasiRoute,
  DashboardMasterPeriodeRoute: DashboardMasterPeriodeRoute,
  DashboardMasterRekeningRoute: DashboardMasterRekeningRoute,
  DashboardMasterRoleRoute: DashboardMasterRoleRoute,
  DashboardMasterSkpdRoute: DashboardMasterSkpdRoute,
  DashboardMasterIndexRoute: DashboardMasterIndexRoute,
}

const DashboardMasterRouteRouteWithChildren =
  DashboardMasterRouteRoute._addFileChildren(DashboardMasterRouteRouteChildren)

interface DashboardRkpdIkuRouteRouteChildren {
  DashboardRkpdIkuIku_capaianRoute: typeof DashboardRkpdIkuIku_capaianRoute
  DashboardRkpdIkuIku_listRoute: typeof DashboardRkpdIkuIku_listRoute
  DashboardRkpdIkuIku_taggingRoute: typeof DashboardRkpdIkuIku_taggingRoute
  DashboardRkpdIkuIndexRoute: typeof DashboardRkpdIkuIndexRoute
}

const DashboardRkpdIkuRouteRouteChildren: DashboardRkpdIkuRouteRouteChildren = {
  DashboardRkpdIkuIku_capaianRoute: DashboardRkpdIkuIku_capaianRoute,
  DashboardRkpdIkuIku_listRoute: DashboardRkpdIkuIku_listRoute,
  DashboardRkpdIkuIku_taggingRoute: DashboardRkpdIkuIku_taggingRoute,
  DashboardRkpdIkuIndexRoute: DashboardRkpdIkuIndexRoute,
}

const DashboardRkpdIkuRouteRouteWithChildren =
  DashboardRkpdIkuRouteRoute._addFileChildren(
    DashboardRkpdIkuRouteRouteChildren,
  )

interface DashboardRkpdRenstraRouteRouteChildren {
  DashboardRkpdRenstraIokRoute: typeof DashboardRkpdRenstraIokRoute
  DashboardRkpdRenstraIopRoute: typeof DashboardRkpdRenstraIopRoute
  DashboardRkpdRenstraIoskRoute: typeof DashboardRkpdRenstraIoskRoute
  DashboardRkpdRenstraIndexRoute: typeof DashboardRkpdRenstraIndexRoute
}

const DashboardRkpdRenstraRouteRouteChildren: DashboardRkpdRenstraRouteRouteChildren =
  {
    DashboardRkpdRenstraIokRoute: DashboardRkpdRenstraIokRoute,
    DashboardRkpdRenstraIopRoute: DashboardRkpdRenstraIopRoute,
    DashboardRkpdRenstraIoskRoute: DashboardRkpdRenstraIoskRoute,
    DashboardRkpdRenstraIndexRoute: DashboardRkpdRenstraIndexRoute,
  }

const DashboardRkpdRenstraRouteRouteWithChildren =
  DashboardRkpdRenstraRouteRoute._addFileChildren(
    DashboardRkpdRenstraRouteRouteChildren,
  )

interface DashboardRkpdRouteRouteChildren {
  DashboardRkpdIkuRouteRoute: typeof DashboardRkpdIkuRouteRouteWithChildren
  DashboardRkpdRenstraRouteRoute: typeof DashboardRkpdRenstraRouteRouteWithChildren
  DashboardRkpdPagu_indikatifRoute: typeof DashboardRkpdPagu_indikatifRoute
  DashboardRkpdRealisasiRoute: typeof DashboardRkpdRealisasiRoute
  DashboardRkpdRenjaRoute: typeof DashboardRkpdRenjaRoute
  DashboardRkpdIndexRoute: typeof DashboardRkpdIndexRoute
}

const DashboardRkpdRouteRouteChildren: DashboardRkpdRouteRouteChildren = {
  DashboardRkpdIkuRouteRoute: DashboardRkpdIkuRouteRouteWithChildren,
  DashboardRkpdRenstraRouteRoute: DashboardRkpdRenstraRouteRouteWithChildren,
  DashboardRkpdPagu_indikatifRoute: DashboardRkpdPagu_indikatifRoute,
  DashboardRkpdRealisasiRoute: DashboardRkpdRealisasiRoute,
  DashboardRkpdRenjaRoute: DashboardRkpdRenjaRoute,
  DashboardRkpdIndexRoute: DashboardRkpdIndexRoute,
}

const DashboardRkpdRouteRouteWithChildren =
  DashboardRkpdRouteRoute._addFileChildren(DashboardRkpdRouteRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardDakRouteRoute: typeof DashboardDakRouteRouteWithChildren
  DashboardKonfigurasiRouteRoute: typeof DashboardKonfigurasiRouteRouteWithChildren
  DashboardMasterRouteRoute: typeof DashboardMasterRouteRouteWithChildren
  DashboardRkpdRouteRoute: typeof DashboardRkpdRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardDakRouteRoute: DashboardDakRouteRouteWithChildren,
  DashboardKonfigurasiRouteRoute: DashboardKonfigurasiRouteRouteWithChildren,
  DashboardMasterRouteRoute: DashboardMasterRouteRouteWithChildren,
  DashboardRkpdRouteRoute: DashboardRkpdRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLogoutRoute: AuthLogoutRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
